package zentropivity.emimablockgame.item;

import java.util.Map;

import com.mojang.brigadier.exceptions.CommandSyntaxException;

import dev.emi.emi.api.EmiRegistry;
import dev.emi.emi.api.stack.Comparison;
import dev.emi.emi.api.stack.EmiStack;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.item.Items;
import net.minecraft.nbt.NbtCompound;
import net.minecraft.nbt.StringNbtReader;

import java.util.HashMap;

public class BlockGameItems {
  private static final Map<String, EmiStack> ITEMS = new HashMap<>();

  public static EmiStack createItem(Item item, String bgItem, String name) {
    ItemStack Stack = new ItemStack(item);
    // Stack.setCount(0);

    String nbt = "{ \"display\": {\"Name\": '{\"text\":\"" + name
        + "\",\"color\":\"white\",\"italic\":false}'}, \"MMOITEMS_ITEM_ID\": \"" + bgItem + "\" }";

    NbtCompound NBT = new NbtCompound();
    try {
      NBT = StringNbtReader.parse(nbt);
    } catch (CommandSyntaxException e) {
      throw new RuntimeException(e);
    }
    Stack.setNbt(NBT);

    EmiStack out = EmiStack.of(Stack).comparison(Comparison.compareNbt());
    ITEMS.put(bgItem, out);

    return out;
  }

  public static final EmiStack ACOLYTE_BOOTS = createItem(Items.LEATHER_BOOTS, "ACOLYTE_BOOTS", "Acolyte Boots"),
      ACOLYTE_CHESTPLATE = createItem(Items.LEATHER_CHESTPLATE, "ACOLYTE_CHESTPLATE", "Acolyte Chestplate"),
      ACOLYTE_HELMET = createItem(Items.LEATHER_HELMET, "ACOLYTE_HELMET", "Acolyte Helmet"),
      ACOLYTE_LEGGINGS = createItem(Items.LEATHER_LEGGINGS, "ACOLYTE_LEGGINGS", "Acolyte Leggings"),
      ANCIENT_POTTERY = createItem(Items.FLOWER_POT, "ANCIENT_POTTERY", "Ancient Pottery"),
      ANIMATED_BONE = createItem(Items.BONE, "ANIMATED_BONE", "Animated Bone"),
      ARCHAEOLOGIST_BOOTS = createItem(Items.LEATHER_BOOTS, "ARCHAEOLOGIST_BOOTS", "Archaeologist Boots"),
      ARCHAEOLOGIST_BOOTS_1 = createItem(Items.LEATHER_BOOTS, "ARCHAEOLOGIST_BOOTS_1", "Archaeologist Boots 1"),
      ARCHAEOLOGIST_BOOTS_2 = createItem(Items.LEATHER_BOOTS, "ARCHAEOLOGIST_BOOTS_2", "Archaeologist Boots 2"),
      ARCHAEOLOGIST_BOOTS_3 = createItem(Items.LEATHER_BOOTS, "ARCHAEOLOGIST_BOOTS_3", "Archaeologist Boots 3"),
      ARCHAEOLOGIST_BOOTS_4 = createItem(Items.LEATHER_BOOTS, "ARCHAEOLOGIST_BOOTS_4", "Archaeologist Boots 4"),
      ARCHAEOLOGIST_BOOTS_5 = createItem(Items.LEATHER_BOOTS, "ARCHAEOLOGIST_BOOTS_5", "Archaeologist Boots 5"),
      ARCHAEOLOGIST_CHESTPLATE = createItem(Items.LEATHER_CHESTPLATE, "ARCHAEOLOGIST_CHESTPLATE",
          "Archaeologist Chestplate"),
      ARCHAEOLOGIST_CHESTPLATE_1 = createItem(Items.LEATHER_CHESTPLATE, "ARCHAEOLOGIST_CHESTPLATE_1",
          "Archaeologist Chestplate 1"),
      ARCHAEOLOGIST_CHESTPLATE_2 = createItem(Items.LEATHER_CHESTPLATE, "ARCHAEOLOGIST_CHESTPLATE_2",
          "Archaeologist Chestplate 2"),
      ARCHAEOLOGIST_CHESTPLATE_3 = createItem(Items.LEATHER_CHESTPLATE, "ARCHAEOLOGIST_CHESTPLATE_3",
          "Archaeologist Chestplate 3"),
      ARCHAEOLOGIST_CHESTPLATE_4 = createItem(Items.LEATHER_CHESTPLATE, "ARCHAEOLOGIST_CHESTPLATE_4",
          "Archaeologist Chestplate 4"),
      ARCHAEOLOGIST_CHESTPLATE_5 = createItem(Items.LEATHER_CHESTPLATE, "ARCHAEOLOGIST_CHESTPLATE_5",
          "Archaeologist Chestplate 5"),
      ARCHAEOLOGIST_HELMET = createItem(Items.LEATHER_HELMET, "ARCHAEOLOGIST_HELMET", "Archaeologist Helmet"),
      ARCHAEOLOGIST_HELMET_1 = createItem(Items.LEATHER_HELMET, "ARCHAEOLOGIST_HELMET_1", "Archaeologist Helmet 1"),
      ARCHAEOLOGIST_HELMET_2 = createItem(Items.LEATHER_HELMET, "ARCHAEOLOGIST_HELMET_2", "Archaeologist Helmet 2"),
      ARCHAEOLOGIST_HELMET_3 = createItem(Items.LEATHER_HELMET, "ARCHAEOLOGIST_HELMET_3", "Archaeologist Helmet 3"),
      ARCHAEOLOGIST_HELMET_4 = createItem(Items.LEATHER_HELMET, "ARCHAEOLOGIST_HELMET_4", "Archaeologist Helmet 4"),
      ARCHAEOLOGIST_HELMET_5 = createItem(Items.LEATHER_HELMET, "ARCHAEOLOGIST_HELMET_5", "Archaeologist Helmet 5"),
      ARCHAEOLOGIST_LEGGINGS = createItem(Items.LEATHER_LEGGINGS, "ARCHAEOLOGIST_LEGGINGS", "Archaeologist Leggings"),
      ARCHAEOLOGIST_LEGGINGS_1 = createItem(Items.LEATHER_LEGGINGS, "ARCHAEOLOGIST_LEGGINGS_1",
          "Archaeologist Leggings 1"),
      ARCHAEOLOGIST_LEGGINGS_2 = createItem(Items.LEATHER_LEGGINGS, "ARCHAEOLOGIST_LEGGINGS_2",
          "Archaeologist Leggings 2"),
      ARCHAEOLOGIST_LEGGINGS_3 = createItem(Items.LEATHER_LEGGINGS, "ARCHAEOLOGIST_LEGGINGS_3",
          "Archaeologist Leggings 3"),
      ARCHAEOLOGIST_LEGGINGS_4 = createItem(Items.LEATHER_LEGGINGS, "ARCHAEOLOGIST_LEGGINGS_4",
          "Archaeologist Leggings 4"),
      ARCHAEOLOGIST_LEGGINGS_5 = createItem(Items.LEATHER_LEGGINGS, "ARCHAEOLOGIST_LEGGINGS_5",
          "Archaeologist Leggings 5"),
      AUGMENT_ARCHAEOLOGY_1 = createItem(Items.LEVER, "AUGMENT_ARCHAEOLOGY_1", "Augment Archaeology 1"),
      AUGMENT_ARCHAEOLOGY_2 = createItem(Items.LEVER, "AUGMENT_ARCHAEOLOGY_2", "Augment Archaeology 2"),
      AUGMENT_ARCHAEOLOGY_3 = createItem(Items.LEVER, "AUGMENT_ARCHAEOLOGY_3", "Augment Archaeology 3"),
      AUGMENT_ARCHAEOLOGY_4 = createItem(Items.LEVER, "AUGMENT_ARCHAEOLOGY_4", "Augment Archaeology 4"),
      AUGMENT_ARCHAEOLOGY_5 = createItem(Items.LEVER, "AUGMENT_ARCHAEOLOGY_5", "Augment Archaeology 5"),
      AUGMENT_FISHING_1 = createItem(Items.CHEST, "AUGMENT_FISHING_1", "Augment Fishing 1"),
      AUGMENT_FISHING_2 = createItem(Items.CHEST, "AUGMENT_FISHING_2", "Augment Fishing 2"),
      AUGMENT_FISHING_3 = createItem(Items.CHEST, "AUGMENT_FISHING_3", "Augment Fishing 3"),
      AUGMENT_FISHING_4 = createItem(Items.CHEST, "AUGMENT_FISHING_4", "Augment Fishing 4"),
      AUGMENT_FISHING_5 = createItem(Items.ENDER_CHEST, "AUGMENT_FISHING_5", "Augment Fishing 5"),
      AUGMENT_HERBALISM_1 = createItem(Items.FLOWER_POT, "AUGMENT_HERBALISM_1", "Augment Herbalism 1"),
      AUGMENT_HERBALISM_2 = createItem(Items.FLOWER_POT, "AUGMENT_HERBALISM_2", "Augment Herbalism 2"),
      AUGMENT_HERBALISM_3 = createItem(Items.FLOWER_POT, "AUGMENT_HERBALISM_3", "Augment Herbalism 3"),
      AUGMENT_HERBALISM_4 = createItem(Items.FLOWER_POT, "AUGMENT_HERBALISM_4", "Augment Herbalism 4"),
      AUGMENT_HERBALISM_5 = createItem(Items.FLOWER_POT, "AUGMENT_HERBALISM_5", "Augment Herbalism 5"),
      AUGMENT_LOGGING_1 = createItem(Items.CLOCK, "AUGMENT_LOGGING_1", "Augment Logging 1"),
      AUGMENT_LOGGING_2 = createItem(Items.CLOCK, "AUGMENT_LOGGING_2", "Augment Logging 2"),
      AUGMENT_LOGGING_3 = createItem(Items.CLOCK, "AUGMENT_LOGGING_3", "Augment Logging 3"),
      AUGMENT_LOGGING_4 = createItem(Items.CLOCK, "AUGMENT_LOGGING_4", "Augment Logging 4"),
      AUGMENT_LOGGING_5 = createItem(Items.CLOCK, "AUGMENT_LOGGING_5", "Augment Logging 5"),
      AUGMENT_MINING_1 = createItem(Items.STICK, "AUGMENT_MINING_1", "Augment Mining 1"),
      AUGMENT_MINING_2 = createItem(Items.LIGHTNING_ROD, "AUGMENT_MINING_2", "Augment Mining 2"),
      AUGMENT_MINING_3 = createItem(Items.END_ROD, "AUGMENT_MINING_3", "Augment Mining 3"),
      AUGMENT_MINING_4 = createItem(Items.SOUL_TORCH, "AUGMENT_MINING_4", "Augment Mining 4"),
      AUGMENT_MINING_5 = createItem(Items.CHAIN, "AUGMENT_MINING_5", "Augment Mining 5"),
      BACON_AND_EGGS = createItem(Items.RABBIT_STEW, "BACON_AND_EGGS", "Bacon And Eggs"),
      BACON_BITS = createItem(Items.COCOA_BEANS, "BACON_BITS", "Bacon Bits"),
      BARK_OAK = createItem(Items.OAK_PRESSURE_PLATE, "BARK_OAK", "Oak Bark"),
      BARK_SPRUCE = createItem(Items.SPRUCE_PRESSURE_PLATE, "BARK_SPRUCE", "Spruce Bark"),
      BARK_BIRCH = createItem(Items.BIRCH_PRESSURE_PLATE, "BARK_BIRCH", "Birch Bark"),
      BARK_MANGROVE = createItem(Items.MANGROVE_PRESSURE_PLATE, "BARK_MANGROVE", "Mangrove Bark"),
      BARK_JUNGLE = createItem(Items.JUNGLE_PRESSURE_PLATE, "BARK_JUNGLE", "Jungle Bark"),
      BARK_ACACIA = createItem(Items.ACACIA_PRESSURE_PLATE, "BARK_ACACIA", "Acacia Bark"),
      BARK_DARK_OAK = createItem(Items.DARK_OAK_PRESSURE_PLATE, "BARK_DARK_OAK", "Dark Oak Bark"),
      BLESSED_WOOL_BOOTS = createItem(Items.LEATHER_BOOTS, "BLESSED_WOOL_BOOTS", "Blessed Wool Boots"),
      BLESSED_WOOL_CHESTPLATE = createItem(Items.LEATHER_CHESTPLATE, "BLESSED_WOOL_CHESTPLATE",
          "Blessed Wool Chestplate"),
      BLESSED_WOOL_HELMET = createItem(Items.LEATHER_HELMET, "BLESSED_WOOL_HELMET", "Blessed Wool Helmet"),
      BLESSED_WOOL_LEGGINGS = createItem(Items.LEATHER_LEGGINGS, "BLESSED_WOOL_LEGGINGS", "Blessed Wool Leggings"),
      BLOODSNOUT_BLADE = createItem(Items.GOLDEN_SWORD, "BLOODSNOUT_BLADE", "Bloodsnout Blade"),
      BLOODSNOUT_BRUTE_BOOTS = createItem(Items.GOLDEN_BOOTS, "BLOODSNOUT_BRUTE_BOOTS", "Bloodsnout Brute Boots"),
      BLOODSNOUT_BRUTE_CHESTPLATE = createItem(Items.GOLDEN_CHESTPLATE, "BLOODSNOUT_BRUTE_CHESTPLATE",
          "Bloodsnout Brute Chestplate"),
      BLOODSNOUT_BRUTE_HELMET = createItem(Items.GOLDEN_HELMET, "BLOODSNOUT_BRUTE_HELMET", "Bloodsnout Brute Helmet"),
      BLOODSNOUT_BRUTE_LEGGINGS = createItem(Items.GOLDEN_LEGGINGS, "BLOODSNOUT_BRUTE_LEGGINGS",
          "Bloodsnout Brute Leggings"),
      BLOODSNOUT_HEALER_BOOTS = createItem(Items.LEATHER_BOOTS, "BLOODSNOUT_HEALER_BOOTS", "Bloodsnout Healer Boots"),
      BLOODSNOUT_HEALER_CHESTPLATE = createItem(Items.LEATHER_CHESTPLATE, "BLOODSNOUT_HEALER_CHESTPLATE",
          "Bloodsnout Healer Chestplate"),
      BLOODSNOUT_HEALER_HELMET = createItem(Items.LEATHER_HELMET, "BLOODSNOUT_HEALER_HELMET",
          "Bloodsnout Healer Helmet"),
      BLOODSNOUT_HEALER_LEGGINGS = createItem(Items.LEATHER_LEGGINGS, "BLOODSNOUT_HEALER_LEGGINGS",
          "Bloodsnout Healer Leggings"),
      BLOODSNOUT_MACE = createItem(Items.BLAZE_ROD, "BLOODSNOUT_MACE", "Bloodsnout Mace"),
      BLOODSNOUT_MAGI_BOOTS = createItem(Items.LEATHER_BOOTS, "BLOODSNOUT_MAGI_BOOTS", "Bloodsnout Magi Boots"),
      BLOODSNOUT_MAGI_CHESTPLATE = createItem(Items.LEATHER_CHESTPLATE, "BLOODSNOUT_MAGI_CHESTPLATE",
          "Bloodsnout Magi Chestplate"),
      BLOODSNOUT_MAGI_HELMET = createItem(Items.LEATHER_HELMET, "BLOODSNOUT_MAGI_HELMET", "Bloodsnout Magi Helmet"),
      BLOODSNOUT_MAGI_LEGGINGS = createItem(Items.LEATHER_LEGGINGS, "BLOODSNOUT_MAGI_LEGGINGS",
          "Bloodsnout Magi Leggings"),
      BLOODSNOUT_SHIELD = createItem(Items.CRIMSON_FUNGUS, "BLOODSNOUT_SHIELD", "Bloodsnout Shield"),
      BLOODSNOUT_SLAYER_BOOTS = createItem(Items.GOLDEN_BOOTS, "BLOODSNOUT_SLAYER_BOOTS", "Bloodsnout Slayer Boots"),
      BLOODSNOUT_SLAYER_CHESTPLATE = createItem(Items.GOLDEN_CHESTPLATE, "BLOODSNOUT_SLAYER_CHESTPLATE",
          "Bloodsnout Slayer Chestplate"),
      BLOODSNOUT_SLAYER_HELMET = createItem(Items.GOLDEN_HELMET, "BLOODSNOUT_SLAYER_HELMET",
          "Bloodsnout Slayer Helmet"),
      BLOODSNOUT_SLAYER_LEGGINGS = createItem(Items.GOLDEN_LEGGINGS, "BLOODSNOUT_SLAYER_LEGGINGS",
          "Bloodsnout Slayer Leggings"),
      BOLT_BACON = createItem(Items.WHITE_DYE, "BOLT_BACON", "Bolt Bacon"),
      BOLT_BRANDED = createItem(Items.WHITE_DYE, "BOLT_BRANDED", "Bolt Branded"),
      BOLT_SANDY = createItem(Items.WHITE_DYE, "BOLT_SANDY", "Bolt Sandy"),
      BOLT_SCORCHING = createItem(Items.WHITE_DYE, "BOLT_SCORCHING", "Bolt Scorching"),
      BOLT_SILK = createItem(Items.WHITE_DYE, "BOLT_SILK", "Bolt Silk"),
      BOLT_SILK_SPARKING = createItem(Items.WHITE_DYE, "BOLT_SILK_SPARKING", "Bolt Silk Sparking"),
      BOLT_SOULFUL = createItem(Items.WHITE_DYE, "BOLT_SOULFUL", "Bolt Soulful"),
      BOLT_WOOL = createItem(Items.WHITE_DYE, "BOLT_WOOL", "Bolt Wool"),
      BOLT_WOOL_BLESSED = createItem(Items.WHITE_DYE, "BOLT_WOOL_BLESSED", "Bolt Wool Blessed"),
      BOLT_WOOL_GREASY = createItem(Items.WHITE_DYE, "BOLT_WOOL_GREASY", "Bolt Wool Greasy"),
      BOLT_WOOL_SANCTIFIED = createItem(Items.WHITE_DYE, "BOLT_WOOL_SANCTIFIED", "Bolt Wool Sanctified"),
      BOLT_WOOL_SANDY = createItem(Items.WHITE_DYE, "BOLT_WOOL_SANDY", "Bolt Wool Sandy"),
      BONES_EVERPOWERFUL = createItem(Items.BONE, "BONES_EVERPOWERFUL", "Bones Everpowerful"),
      BONE_BROTH = createItem(Items.POTION, "BONE_BROTH", "Bone Broth"),
      BONE_SHIELD = createItem(Items.BONE, "BONE_SHIELD", "Bone Shield"),
      BOTANIST_BOOTS = createItem(Items.LEATHER_BOOTS, "BOTANIST_BOOTS", "Botanist Boots"),
      BOTANIST_BOOTS_1 = createItem(Items.LEATHER_BOOTS, "BOTANIST_BOOTS_1", "Botanist Boots 1"),
      BOTANIST_BOOTS_2 = createItem(Items.LEATHER_BOOTS, "BOTANIST_BOOTS_2", "Botanist Boots 2"),
      BOTANIST_BOOTS_3 = createItem(Items.LEATHER_BOOTS, "BOTANIST_BOOTS_3", "Botanist Boots 3"),
      BOTANIST_BOOTS_4 = createItem(Items.LEATHER_BOOTS, "BOTANIST_BOOTS_4", "Botanist Boots 4"),
      BOTANIST_BOOTS_5 = createItem(Items.LEATHER_BOOTS, "BOTANIST_BOOTS_5", "Botanist Boots 5"),
      BOTANIST_CHESTPLATE = createItem(Items.LEATHER_CHESTPLATE, "BOTANIST_CHESTPLATE", "Botanist Chestplate"),
      BOTANIST_CHESTPLATE_1 = createItem(Items.LEATHER_CHESTPLATE, "BOTANIST_CHESTPLATE_1", "Botanist Chestplate 1"),
      BOTANIST_CHESTPLATE_2 = createItem(Items.LEATHER_CHESTPLATE, "BOTANIST_CHESTPLATE_2", "Botanist Chestplate 2"),
      BOTANIST_CHESTPLATE_3 = createItem(Items.LEATHER_CHESTPLATE, "BOTANIST_CHESTPLATE_3", "Botanist Chestplate 3"),
      BOTANIST_CHESTPLATE_4 = createItem(Items.LEATHER_CHESTPLATE, "BOTANIST_CHESTPLATE_4", "Botanist Chestplate 4"),
      BOTANIST_CHESTPLATE_5 = createItem(Items.LEATHER_CHESTPLATE, "BOTANIST_CHESTPLATE_5", "Botanist Chestplate 5"),
      BOTANIST_HELMET = createItem(Items.LEATHER_HELMET, "BOTANIST_HELMET", "Botanist Helmet"),
      BOTANIST_HELMET_1 = createItem(Items.LEATHER_HELMET, "BOTANIST_HELMET_1", "Botanist Helmet 1"),
      BOTANIST_HELMET_2 = createItem(Items.LEATHER_HELMET, "BOTANIST_HELMET_2", "Botanist Helmet 2"),
      BOTANIST_HELMET_3 = createItem(Items.LEATHER_HELMET, "BOTANIST_HELMET_3", "Botanist Helmet 3"),
      BOTANIST_HELMET_4 = createItem(Items.LEATHER_HELMET, "BOTANIST_HELMET_4", "Botanist Helmet 4"),
      BOTANIST_HELMET_5 = createItem(Items.LEATHER_HELMET, "BOTANIST_HELMET_5", "Botanist Helmet 5"),
      BOTANIST_LEGGINGS = createItem(Items.LEATHER_LEGGINGS, "BOTANIST_LEGGINGS", "Botanist Leggings"),
      BOTANIST_LEGGINGS_1 = createItem(Items.LEATHER_LEGGINGS, "BOTANIST_LEGGINGS_1", "Botanist Leggings 1"),
      BOTANIST_LEGGINGS_2 = createItem(Items.LEATHER_LEGGINGS, "BOTANIST_LEGGINGS_2", "Botanist Leggings 2"),
      BOTANIST_LEGGINGS_3 = createItem(Items.LEATHER_LEGGINGS, "BOTANIST_LEGGINGS_3", "Botanist Leggings 3"),
      BOTANIST_LEGGINGS_4 = createItem(Items.LEATHER_LEGGINGS, "BOTANIST_LEGGINGS_4", "Botanist Leggings 4"),
      BOTANIST_LEGGINGS_5 = createItem(Items.LEATHER_LEGGINGS, "BOTANIST_LEGGINGS_5", "Botanist Leggings 5"),
      BOTTLE_EARTH = createItem(Items.SPLASH_POTION, "BOTTLE_EARTH", "Bottle Earth"),
      BOTTLE_FROST = createItem(Items.SPLASH_POTION, "BOTTLE_FROST", "Bottle Frost"),
      BOTTLE_FROST_GREATER = createItem(Items.SPLASH_POTION, "BOTTLE_FROST_GREATER", "Bottle Frost Greater"),
      BOTTLE_HAUNTED = createItem(Items.POTION, "BOTTLE_HAUNTED", "Bottle Haunted"),
      BOTTLE_HEALING = createItem(Items.POTION, "BOTTLE_HEALING", "Bottle Healing"),
      BOTTLE_HEALING_GLOWING = createItem(Items.POTION, "BOTTLE_HEALING_GLOWING", "Bottle Healing Glowing"),
      BOTTLE_LAPIS = createItem(Items.POTION, "BOTTLE_LAPIS", "Bottle Lapis"),
      BOTTLE_LAVA = createItem(Items.SPLASH_POTION, "BOTTLE_LAVA", "Bottle Lava"),
      BOTTLE_LAVA_GREATER = createItem(Items.SPLASH_POTION, "BOTTLE_LAVA_GREATER", "Bottle Lava Greater"),
      BOTTLE_REDSTONE = createItem(Items.POTION, "BOTTLE_REDSTONE", "Bottle Redstone"),
      BOTTLE_WATER_CLEAN = createItem(Items.POTION, "BOTTLE_WATER_CLEAN", "Bottle Water Clean"),
      BOTTLE_WIND = createItem(Items.SPLASH_POTION, "BOTTLE_WIND", "Bottle Wind"),
      BRANDED_SOUL = createItem(Items.BLAZE_POWDER, "BRANDED_SOUL", "Branded Soul"),
      BRASS_AXE = createItem(Items.STONE_AXE, "BRASS_AXE", "Brass Axe"),
      BRASS_FISHINGPOLE = createItem(Items.FISHING_ROD, "BRASS_FISHINGPOLE", "Brass Fishingpole"),
      BRASS_HOE = createItem(Items.STONE_HOE, "BRASS_HOE", "Brass Hoe"),
      BRASS_PICKAXE = createItem(Items.STONE_PICKAXE, "BRASS_PICKAXE", "Brass Pickaxe"),
      BRASS_SHOVEL = createItem(Items.STONE_SHOVEL, "BRASS_SHOVEL", "Brass Shovel"),
      BURNING_CORE = createItem(Items.REDSTONE_BLOCK, "BURNING_CORE", "Burning Core"),
      BUTTER = createItem(Items.GOLD_INGOT, "BUTTER", "Butter"),
      BUTTER_FRIED_BEEF = createItem(Items.COOKED_BEEF, "BUTTER_FRIED_BEEF", "Butter Fried Beef"),
      BUTTER_FRIED_CHICKEN = createItem(Items.COOKED_CHICKEN, "BUTTER_FRIED_CHICKEN", "Butter Fried Chicken"),
      BUTTER_FRIED_COD = createItem(Items.COOKED_COD, "BUTTER_FRIED_COD", "Butter Fried Cod"),
      BUTTER_FRIED_MUTTON = createItem(Items.COOKED_MUTTON, "BUTTER_FRIED_MUTTON", "Butter Fried Mutton"),
      BUTTER_FRIED_PORKCHOP = createItem(Items.COOKED_PORKCHOP, "BUTTER_FRIED_PORKCHOP", "Butter Fried Porkchop"),
      BUTTER_FRIED_PUFFERFISH = createItem(Items.PUFFERFISH, "BUTTER_FRIED_PUFFERFISH", "Butter Fried Pufferfish"),
      BUTTER_FRIED_RABBIT = createItem(Items.COOKED_RABBIT, "BUTTER_FRIED_RABBIT", "Butter Fried Rabbit"),
      BUTTER_FRIED_SALMON = createItem(Items.COOKED_SALMON, "BUTTER_FRIED_SALMON", "Butter Fried Salmon"),
      BUTTER_FRIED_TROPICAL_FISH = createItem(Items.TROPICAL_FISH, "BUTTER_FRIED_TROPICAL_FISH",
          "Butter Fried Tropical Fish"),
      CACTUS_BOOTS = createItem(Items.LEATHER_BOOTS, "CACTUS_BOOTS", "Cactus Boots"),
      CACTUS_CHESTPLATE = createItem(Items.LEATHER_CHESTPLATE, "CACTUS_CHESTPLATE", "Cactus Chestplate"),
      CACTUS_HELMET = createItem(Items.LEATHER_HELMET, "CACTUS_HELMET", "Cactus Helmet"),
      CACTUS_LEGGINGS = createItem(Items.LEATHER_LEGGINGS, "CACTUS_LEGGINGS", "Cactus Leggings"),
      CACTUS_SWORD = createItem(Items.WOODEN_SWORD, "CACTUS_SWORD", "Cactus Sword"),
      CANDYFISH = createItem(Items.TROPICAL_FISH, "CANDYFISH", "Candyfish"),
      CANDY_CORN = createItem(Items.PUMPKIN_SEEDS, "CANDY_CORN", "Candy Corn"),
      CHILLED_HIDE = createItem(Items.LEATHER, "CHILLED_HIDE", "Chilled Hide"),
      CHOCOLATE_RABBIT = createItem(Items.COOKED_RABBIT, "CHOCOLATE_RABBIT", "Chocolate Rabbit"),
      CINDERS_BOOTS = createItem(Items.LEATHER_BOOTS, "CINDERS_BOOTS", "Cinders Boots"),
      CINDERS_CHESTPLATE = createItem(Items.LEATHER_CHESTPLATE, "CINDERS_CHESTPLATE", "Cinders Chestplate"),
      CINDERS_FIREBRAND = createItem(Items.REDSTONE_TORCH, "CINDERS_FIREBRAND", "Cinders Firebrand"),
      CINDERS_HELMET = createItem(Items.LEATHER_HELMET, "CINDERS_HELMET", "Cinders Helmet"),
      CINDERS_LEGGINGS = createItem(Items.LEATHER_LEGGINGS, "CINDERS_LEGGINGS", "Cinders Leggings"),
      COAGULATED_MASS = createItem(Items.RED_DYE, "COAGULATED_MASS", "Coagulated Mass"),
      COMMON_SHELL = createItem(Items.NAUTILUS_SHELL, "COMMON_SHELL", "Common Shell"),
      COMPRESSED_CRYSTAL = createItem(Items.AMETHYST_SHARD, "COMPRESSED_CRYSTAL", "Compressed Crystal"),
      COMPRESSED_DIAMOND = createItem(Items.DIAMOND, "COMPRESSED_DIAMOND", "Compressed Diamond"),
      COOKIE_DOUGH = createItem(Items.BROWN_DYE, "COOKIE_DOUGH", "Cookie Dough"),
      COPPER_BOOTS = createItem(Items.LEATHER_BOOTS, "COPPER_BOOTS", "Copper Boots"),
      COPPER_CHESTPLATE = createItem(Items.LEATHER_CHESTPLATE, "COPPER_CHESTPLATE", "Copper Chestplate"),
      COPPER_HELMET = createItem(Items.LEATHER_HELMET, "COPPER_HELMET", "Copper Helmet"),
      COPPER_LEGGINGS = createItem(Items.LEATHER_LEGGINGS, "COPPER_LEGGINGS", "Copper Leggings"),
      COPPER_MACE = createItem(Items.LIGHTNING_ROD, "COPPER_MACE", "Copper Mace"),
      COPPER_SHIELD = createItem(Items.RAW_COPPER, "COPPER_SHIELD", "Copper Shield"),
      CORRUPTED_SHARD = createItem(Items.ECHO_SHARD, "CORRUPTED_SHARD", "Corrupted Shard"),
      CORRUPTED_SOUL = createItem(Items.ENDER_EYE, "CORRUPTED_SOUL", "Corrupted Soul"),
      CRUMBLING_EARTH = createItem(Items.CHARCOAL, "CRUMBLING_EARTH", "Crumbling Earth"),
      CRYSTAL_HIDE = createItem(Items.LEATHER, "CRYSTAL_HIDE", "Crystal Hide"),
      CURIOUS_DEVICE = createItem(Items.CONDUIT, "CURIOUS_DEVICE", "Curious Device"),
      CURSED_SAND = createItem(Items.GLOWSTONE_DUST, "CURSED_SAND", "Cursed Sand"),
      DANCING_SPARK = createItem(Items.BLAZE_POWDER, "DANCING_SPARK", "Dancing Spark"),
      DELICIOUS_BISCUIT = createItem(Items.BAKED_POTATO, "DELICIOUS_BISCUIT", "Delicious Biscuit"),
      DIAMOND_BOOTS = createItem(Items.DIAMOND_BOOTS, "DIAMOND_BOOTS", "Diamond Boots"),
      DIAMOND_CHESTPLATE = createItem(Items.DIAMOND_CHESTPLATE, "DIAMOND_CHESTPLATE", "Diamond Chestplate"),
      DIAMOND_HELMET = createItem(Items.DIAMOND_HELMET, "DIAMOND_HELMET", "Diamond Helmet"),
      DIAMOND_LEGGINGS = createItem(Items.DIAMOND_LEGGINGS, "DIAMOND_LEGGINGS", "Diamond Leggings"),
      DIAMOND_SHIELD = createItem(Items.DIAMOND, "DIAMOND_SHIELD", "Diamond Shield"),
      DOUGH = createItem(Items.BROWN_DYE, "DOUGH", "Dough"),
      EARTHEN_HEART = createItem(Items.TURTLE_EGG, "EARTHEN_HEART", "Earthen Heart"),
      EASTER_LAMB = createItem(Items.COOKED_MUTTON, "EASTER_LAMB", "Easter Lamb"),
      EGGNOG = createItem(Items.POTION, "EGGNOG", "Eggnog"),
      ESSENCE_CORRUPTED = createItem(Items.BLACK_DYE, "ESSENCE_CORRUPTED", "Corrupted Essence"),
      ESSENCE_ROCKY = createItem(Items.BROWN_DYE, "ESSENCE_EARTH", "Rocky Essence"),
      ESSENCE_FIERY = createItem(Items.RED_DYE, "ESSENCE_FIRE", "Fiery Essence"),
      ESSENCE_VIBRANT = createItem(Items.GHAST_TEAR, "ESSENCE_LIFE", "Vibrant Essence"),
      ESSENCE_DAMP = createItem(Items.BLUE_DYE, "ESSENCE_WATER", "Damp Essence"),
      ESSENCE_FLEETING = createItem(Items.LIGHT_GRAY_DYE, "ESSENCE_WIND", "Fleeting Essence"),
      FANCY_SHELL = createItem(Items.NAUTILUS_SHELL, "FANCY_SHELL", "Fancy Shell"),
      FAT_CARROT = createItem(Items.CARROT, "FAT_CARROT", "Fat Carrot"),
      FINNY_BONE = createItem(Items.PRISMARINE_CRYSTALS, "FINNY_BONE", "Finny Bone"),
      FINS_EVERFLAPPING = createItem(Items.PRISMARINE_SHARD, "FINS_EVERFLAPPING", "Fins Everflapping"),
      FISHERMAN_BOOTS = createItem(Items.LEATHER_BOOTS, "FISHERMAN_BOOTS", "Fisherman Boots"),
      FISHERMAN_BOOTS_1 = createItem(Items.LEATHER_BOOTS, "FISHERMAN_BOOTS_1", "Fisherman Boots 1"),
      FISHERMAN_BOOTS_2 = createItem(Items.LEATHER_BOOTS, "FISHERMAN_BOOTS_2", "Fisherman Boots 2"),
      FISHERMAN_BOOTS_3 = createItem(Items.LEATHER_BOOTS, "FISHERMAN_BOOTS_3", "Fisherman Boots 3"),
      FISHERMAN_BOOTS_4 = createItem(Items.LEATHER_BOOTS, "FISHERMAN_BOOTS_4", "Fisherman Boots 4"),
      FISHERMAN_BOOTS_5 = createItem(Items.LEATHER_BOOTS, "FISHERMAN_BOOTS_5", "Fisherman Boots 5"),
      FISHERMAN_CHESTPLATE = createItem(Items.LEATHER_CHESTPLATE, "FISHERMAN_CHESTPLATE", "Fisherman Chestplate"),
      FISHERMAN_CHESTPLATE_1 = createItem(Items.LEATHER_CHESTPLATE, "FISHERMAN_CHESTPLATE_1", "Fisherman Chestplate 1"),
      FISHERMAN_CHESTPLATE_2 = createItem(Items.LEATHER_CHESTPLATE, "FISHERMAN_CHESTPLATE_2", "Fisherman Chestplate 2"),
      FISHERMAN_CHESTPLATE_3 = createItem(Items.LEATHER_CHESTPLATE, "FISHERMAN_CHESTPLATE_3", "Fisherman Chestplate 3"),
      FISHERMAN_CHESTPLATE_4 = createItem(Items.LEATHER_CHESTPLATE, "FISHERMAN_CHESTPLATE_4", "Fisherman Chestplate 4"),
      FISHERMAN_CHESTPLATE_5 = createItem(Items.LEATHER_CHESTPLATE, "FISHERMAN_CHESTPLATE_5", "Fisherman Chestplate 5"),
      FISHERMAN_HELMET = createItem(Items.LEATHER_HELMET, "FISHERMAN_HELMET", "Fisherman Helmet"),
      FISHERMAN_HELMET_1 = createItem(Items.LEATHER_HELMET, "FISHERMAN_HELMET_1", "Fisherman Helmet 1"),
      FISHERMAN_HELMET_2 = createItem(Items.LEATHER_HELMET, "FISHERMAN_HELMET_2", "Fisherman Helmet 2"),
      FISHERMAN_HELMET_3 = createItem(Items.LEATHER_HELMET, "FISHERMAN_HELMET_3", "Fisherman Helmet 3"),
      FISHERMAN_HELMET_4 = createItem(Items.LEATHER_HELMET, "FISHERMAN_HELMET_4", "Fisherman Helmet 4"),
      FISHERMAN_HELMET_5 = createItem(Items.LEATHER_HELMET, "FISHERMAN_HELMET_5", "Fisherman Helmet 5"),
      FISHERMAN_LEGGINGS = createItem(Items.LEATHER_LEGGINGS, "FISHERMAN_LEGGINGS", "Fisherman Leggings"),
      FISHERMAN_LEGGINGS_1 = createItem(Items.LEATHER_LEGGINGS, "FISHERMAN_LEGGINGS_1", "Fisherman Leggings 1"),
      FISHERMAN_LEGGINGS_2 = createItem(Items.LEATHER_LEGGINGS, "FISHERMAN_LEGGINGS_2", "Fisherman Leggings 2"),
      FISHERMAN_LEGGINGS_3 = createItem(Items.LEATHER_LEGGINGS, "FISHERMAN_LEGGINGS_3", "Fisherman Leggings 3"),
      FISHERMAN_LEGGINGS_4 = createItem(Items.LEATHER_LEGGINGS, "FISHERMAN_LEGGINGS_4", "Fisherman Leggings 4"),
      FISHERMAN_LEGGINGS_5 = createItem(Items.LEATHER_LEGGINGS, "FISHERMAN_LEGGINGS_5", "Fisherman Leggings 5"),
      FISH_BADFISH = createItem(Items.COD, "FISH_BADFISH", "Fish Badfish"),
      FISH_BAMBOOZLE = createItem(Items.COD, "FISH_BAMBOOZLE", "Fish Bamboozle"),
      FISH_BLUESFISH = createItem(Items.COD, "FISH_BLUESFISH", "Fish Bluesfish"),
      FISH_DARKFISH = createItem(Items.COD, "FISH_DARKFISH", "Fish Darkfish"),
      FISH_DRYFISH = createItem(Items.COD, "FISH_DRYFISH", "Fish Dryfish"),
      FISH_FUNGALFISH = createItem(Items.TROPICAL_FISH, "FISH_FUNGALFISH", "Fish Fungalfish"),
      FISH_GLOWFISH = createItem(Items.TROPICAL_FISH, "FISH_GLOWFISH", "Fish Glowfish"),
      FISH_LEATHER = createItem(Items.LEATHER, "FISH_LEATHER", "Fish Leather"),
      FISH_PEPPERFISH = createItem(Items.SALMON, "FISH_PEPPERFISH", "Fish Pepperfish"),
      FISH_SALTFISH = createItem(Items.COD, "FISH_SALTFISH", "Fish Saltfish"),
      FISH_STONEFISH = createItem(Items.COD, "FISH_STONEFISH", "Fish Stonefish"),
      FISH_WOODFISH = createItem(Items.COD, "FISH_WOODFISH", "Fish Woodfish"),
      FLICKERING_FROST = createItem(Items.NETHER_STAR, "FLICKERING_FROST", "Flickering Frost"),
      FLOUR = createItem(Items.SUGAR, "FLOUR", "Flour"),
      FOCUS_BLOODSNOUT = createItem(Items.MAGMA_CREAM, "FOCUS_BLOODSNOUT", "Focus Bloodsnout"),
      FOCUS_CINDERS = createItem(Items.BLAZE_POWDER, "FOCUS_CINDERS", "Focus Cinders"),
      FOCUS_DJEDI = createItem(Items.BLAZE_POWDER, "FOCUS_DJEDI", "Focus Djedi"),
      FOCUS_FROST = createItem(Items.SNOWBALL, "FOCUS_FROST", "Focus Frost"),
      FOCUS_FROSTSLIME = createItem(Items.SLIME_BLOCK, "FOCUS_FROSTSLIME", "Focus Frostslime"),
      FOCUS_SLIME = createItem(Items.SLIME_BALL, "FOCUS_SLIME", "Focus Slime"),
      FOCUS_TRINITY = createItem(Items.MAGMA_CREAM, "FOCUS_TRINITY", "Focus Trinity"),
      FOCUS_UNSETTLING = createItem(Items.SKELETON_SKULL, "FOCUS_UNSETTLING", "Focus Unsettling"),
      FRAGILE_AXE = createItem(Items.DIAMOND_AXE, "FRAGILE_AXE", "Fragile Axe"),
      FRAGILE_HOE = createItem(Items.DIAMOND_HOE, "FRAGILE_HOE", "Fragile Hoe"),
      FRAGILE_PICKAXE = createItem(Items.DIAMOND_PICKAXE, "FRAGILE_PICKAXE", "Fragile Pickaxe"),
      FRAGILE_SHOVEL = createItem(Items.DIAMOND_SHOVEL, "FRAGILE_SHOVEL", "Fragile Shovel"),
      FROZEN_HIDE = createItem(Items.LEATHER, "FROZEN_HIDE", "Frozen Hide"),
      FROZEN_SOUL = createItem(Items.NETHER_STAR, "FROZEN_SOUL", "Frozen Soul"),
      FROZEN_STAR = createItem(Items.NETHER_STAR, "FROZEN_STAR", "Frozen Star"),
      FILTER = createItem(Items.STICK, "Filter", "Filter"),
      GIANT_GINGERBREAD_COOKIE = createItem(Items.COOKIE, "GIANT_GINGERBREAD_COOKIE", "Giant Gingerbread Cookie"),
      GINGERBREAD_BOOTS_2022 = createItem(Items.LEATHER_BOOTS, "GINGERBREAD_BOOTS_2022", "Gingerbread Boots 2022"),
      GINGERBREAD_CHESTPLATE_2022 = createItem(Items.LEATHER_CHESTPLATE, "GINGERBREAD_CHESTPLATE_2022",
          "Gingerbread Chestplate 2022"),
      GINGERBREAD_HELMET_2022 = createItem(Items.LEATHER_HELMET, "GINGERBREAD_HELMET_2022", "Gingerbread Helmet 2022"),
      GINGERBREAD_LEGGINGS_2022 = createItem(Items.LEATHER_LEGGINGS, "GINGERBREAD_LEGGINGS_2022",
          "Gingerbread Leggings 2022"),
      GLOWING_MOTE = createItem(Items.SUNFLOWER, "GLOWING_MOTE", "Glowing Mote"),
      GOLDEN_BEETROOT = createItem(Items.BEETROOT, "GOLDEN_BEETROOT", "Golden Beetroot"),
      GOLDEN_BREAD = createItem(Items.BREAD, "GOLDEN_BREAD", "Golden Bread"),
      GOLDEN_CARP = createItem(Items.TROPICAL_FISH, "GOLDEN_CARP", "Golden Carp"),
      GOLDEN_DOUGH = createItem(Items.ORANGE_DYE, "GOLDEN_DOUGH", "Golden Dough"),
      GOLDEN_FLOUR = createItem(Items.GLOWSTONE_DUST, "GOLDEN_FLOUR", "Golden Flour"),
      GOLDEN_GRAVY = createItem(Items.POTION, "GOLDEN_GRAVY", "Golden Gravy"),
      GOLDEN_GUPPY = createItem(Items.COD, "GOLDEN_GUPPY", "Golden Guppy"),
      GOLDEN_POTATO = createItem(Items.POTATO, "GOLDEN_POTATO", "Golden Potato"),
      GOLDEN_POTATOES_AND_GOLDEN_GRAVY = createItem(Items.BAKED_POTATO, "GOLDEN_POTATOES_AND_GOLDEN_GRAVY",
          "Golden Potatoes And Golden Gravy"),
      GOLDEN_POTATOES_AND_GOLDEN_GRAVY_ANIMATED = createItem(Items.BAKED_POTATO,
          "GOLDEN_POTATOES_AND_GOLDEN_GRAVY_ANIMATED", "Golden Potatoes And Golden Gravy Animated"),
      GOLDEN_POTATOES_AND_GRAVY = createItem(Items.BAKED_POTATO, "GOLDEN_POTATOES_AND_GRAVY",
          "Golden Potatoes And Gravy"),
      GOLDEN_POTATOES_AND_SENTIENT_GRAVY = createItem(Items.BAKED_POTATO, "GOLDEN_POTATOES_AND_SENTIENT_GRAVY",
          "Golden Potatoes And Sentient Gravy"),
      GOLDEN_PUFFERFISH = createItem(Items.PUFFERFISH, "GOLDEN_PUFFERFISH", "Golden Pufferfish"),
      GOLDEN_RING = createItem(Items.SUNFLOWER, "GOLDEN_RING", "Golden Ring"),
      GOLDEN_WHEAT = createItem(Items.WHEAT, "GOLDEN_WHEAT", "Golden Wheat"),
      GOLD_BRICK = createItem(Items.GOLD_INGOT, "GOLD_BRICK", "Gold Brick"),
      GOLD_COIN = createItem(Items.GOLD_NUGGET, "GOLD_COIN", "Gold Coin"),
      GRAVY = createItem(Items.POTION, "GRAVY", "Gravy"),
      GREASY_HIDE = createItem(Items.LEATHER, "GREASY_HIDE", "Greasy Hide"),
      GRILLED_APPLE = createItem(Items.APPLE, "GRILLED_APPLE", "Grilled Apple"),
      GRILLED_BEETROOT = createItem(Items.BEETROOT, "GRILLED_BEETROOT", "Grilled Beetroot"),
      GRILLED_CARROT = createItem(Items.CARROT, "GRILLED_CARROT", "Grilled Carrot"),
      GRILLED_COOKIE = createItem(Items.COOKIE, "GRILLED_COOKIE", "Grilled Cookie"),
      GRILLED_GOLDEN_BEETROOT = createItem(Items.BEETROOT, "GRILLED_GOLDEN_BEETROOT", "Grilled Golden Beetroot"),
      GRILLED_GOLDEN_POTATO = createItem(Items.BAKED_POTATO, "GRILLED_GOLDEN_POTATO", "Grilled Golden Potato"),
      GRILLED_MUSHROOM = createItem(Items.BAKED_POTATO, "GRILLED_MUSHROOM", "Grilled Mushroom"),
      GRILLED_PLAIN_CHICKEN = createItem(Items.COOKED_CHICKEN, "GRILLED_PLAIN_CHICKEN", "Grilled Plain Chicken"),
      GRILLED_PLAIN_COD = createItem(Items.COOKED_COD, "GRILLED_PLAIN_COD", "Grilled Plain Cod"),
      GRILLED_PLAIN_MUTTON = createItem(Items.COOKED_MUTTON, "GRILLED_PLAIN_MUTTON", "Grilled Plain Mutton"),
      GRILLED_PLAIN_PORKCHOP = createItem(Items.COOKED_PORKCHOP, "GRILLED_PLAIN_PORKCHOP", "Grilled Plain Porkchop"),
      GRILLED_PLAIN_RABBIT = createItem(Items.COOKED_RABBIT, "GRILLED_PLAIN_RABBIT", "Grilled Plain Rabbit"),
      GRILLED_PLAIN_SALMON = createItem(Items.COOKED_SALMON, "GRILLED_PLAIN_SALMON", "Grilled Plain Salmon"),
      GRILLED_PLAIN_STEAK = createItem(Items.COOKED_BEEF, "GRILLED_PLAIN_STEAK", "Grilled Plain Steak"),
      GRILLED_PLAIN_TROPICAL_FISH = createItem(Items.COOKED_COD, "GRILLED_PLAIN_TROPICAL_FISH",
          "Grilled Plain Tropical Fish"),
      GRILLED_POTATO = createItem(Items.BAKED_POTATO, "GRILLED_POTATO", "Grilled Potato"),
      GRILLED_STUFFED_MUSHROOM = createItem(Items.BAKED_POTATO, "GRILLED_STUFFED_MUSHROOM", "Grilled Stuffed Mushroom"),
      HAUNTED_HIDE = createItem(Items.LEATHER, "HAUNTED_HIDE", "Haunted Hide"),
      HEKA_BOOTS = createItem(Items.LEATHER_BOOTS, "HEKA_BOOTS", "Heka Boots"),
      HEKA_CHESTPLATE = createItem(Items.LEATHER_CHESTPLATE, "HEKA_CHESTPLATE", "Heka Chestplate"),
      HEKA_HELMET = createItem(Items.LEATHER_HELMET, "HEKA_HELMET", "Heka Helmet"),
      HEKA_LEGGINGS = createItem(Items.LEATHER_LEGGINGS, "HEKA_LEGGINGS", "Heka Leggings"),
      HORRID_BOOTS = createItem(Items.NETHERITE_BOOTS, "HORRID_BOOTS", "Horrid Boots"),
      HORRID_CHESTPLATE = createItem(Items.NETHERITE_CHESTPLATE, "HORRID_CHESTPLATE", "Horrid Chestplate"),
      HORRID_HELMET = createItem(Items.NETHERITE_HELMET, "HORRID_HELMET", "Horrid Helmet"),
      HORRID_LEGGINGS = createItem(Items.NETHERITE_LEGGINGS, "HORRID_LEGGINGS", "Horrid Leggings"),
      HOT_CHOCOLATE = createItem(Items.POTION, "HOT_CHOCOLATE", "Hot Chocolate"),
      HOT_CROSS_BUN = createItem(Items.BREAD, "HOT_CROSS_BUN", "Hot Cross Bun"),
      IMPLEMENT_BELL = createItem(Items.BELL, "IMPLEMENT_BELL", "Implement Bell"),
      IMPLEMENT_BRAND = createItem(Items.SOUL_TORCH, "IMPLEMENT_BRAND", "Implement Brand"),
      IMPLEMENT_CALLER = createItem(Items.SOUL_LANTERN, "IMPLEMENT_CALLER", "Implement Caller"),
      IMPLEMENT_CAUTERIZING = createItem(Items.TORCH, "IMPLEMENT_CAUTERIZING", "Implement Cauterizing"),
      IMPLEMENT_GUIDING = createItem(Items.LANTERN, "IMPLEMENT_GUIDING", "Implement Guiding"),
      IMPLEMENT_HEKA = createItem(Items.BREWING_STAND, "IMPLEMENT_HEKA", "Implement Heka"),
      INCANTATION_ROTTENMAW_1 = createItem(Items.PAPER, "INCANTATION_ROTTENMAW_1", "Incantation Rottenmaw 1"),
      INCANTATION_ROTTENMAW_5 = createItem(Items.PAPER, "INCANTATION_ROTTENMAW_5", "Incantation Rottenmaw 5"),
      INFUSED_CRYSTAL = createItem(Items.AMETHYST_SHARD, "INFUSED_CRYSTAL", "Infused Crystal"),
      INFUSED_DIAMOND = createItem(Items.DIAMOND, "INFUSED_DIAMOND", "Infused Diamond"),
      JAMMY_BUTTER_TOAST = createItem(Items.BREAD, "JAMMY_BUTTER_TOAST", "Jammy Butter Toast"),
      JAM_GLOWBERRY = createItem(Items.POTION, "JAM_GLOWBERRY", "Jam Glowberry"),
      JAM_SWEETBERRY = createItem(Items.POTION, "JAM_SWEETBERRY", "Jam Sweetberry"),
      KEY_INERT_ROTTENMAW = createItem(Items.NETHERITE_INGOT, "KEY_INERT_ROTTENMAW", "Key Inert Rottenmaw"),
      KEY_ROTTENMAW_1 = createItem(Items.NETHERITE_INGOT, "KEY_ROTTENMAW_1", "Key Rottenmaw 1"),
      KEY_ROTTENMAW_2 = createItem(Items.NETHERITE_INGOT, "KEY_ROTTENMAW_2", "Key Rottenmaw 2"),
      KEY_ROTTENMAW_3 = createItem(Items.NETHERITE_INGOT, "KEY_ROTTENMAW_3", "Key Rottenmaw 3"),
      KEY_ROTTENMAW_4 = createItem(Items.NETHERITE_INGOT, "KEY_ROTTENMAW_4", "Key Rottenmaw 4"),
      KEY_ROTTENMAW_5 = createItem(Items.NETHERITE_INGOT, "KEY_ROTTENMAW_5", "Key Rottenmaw 5"),
      KEY_ROTTENMAW_6 = createItem(Items.NETHERITE_INGOT, "KEY_ROTTENMAW_6", "Key Rottenmaw 6"),
      KEY_ROTTENMAW_7 = createItem(Items.NETHERITE_INGOT, "KEY_ROTTENMAW_7", "Key Rottenmaw 7"),
      KEY_ROTTENMAW_8 = createItem(Items.NETHERITE_INGOT, "KEY_ROTTENMAW_8", "Key Rottenmaw 8"),
      KROGNARS_BLADE = createItem(Items.GOLDEN_SWORD, "KROGNARS_BLADE", "Krognar's Blade"),
      KROGNARS_BOOTS = createItem(Items.GOLDEN_BOOTS, "KROGNARS_BOOTS", "Krognar's Boots"),
      KROGNARS_CHESTPLATE = createItem(Items.GOLDEN_CHESTPLATE, "KROGNARS_CHESTPLATE", "Krognar's Chestplate"),
      KROGNARS_CLEAVER = createItem(Items.GOLDEN_AXE, "KROGNARS_CLEAVER", "Krognar's Cleaver"),
      KROGNARS_HELMET = createItem(Items.GOLDEN_HELMET, "KROGNARS_HELMET", "Krognar's Helmet"),
      KROGNARS_LEGGINGS = createItem(Items.GOLDEN_LEGGINGS, "KROGNARS_LEGGINGS", "Krognar's Leggings"),
      KROGNARS_MACE = createItem(Items.CHAIN, "KROGNARS_MACE", "Krognar's Mace"),
      KROGNARS_BASTION_COMPASS = createItem(Items.STICK, "Krognars Bastion - Compass", "Krognar's Bastion - Compass"),
      LAMP_EVERBURNING = createItem(Items.SOUL_LANTERN, "LAMP_EVERBURNING", "Lamp Everburning"),
      LEATHER_SCRAPS = createItem(Items.NETHERITE_SCRAP, "LEATHER_SCRAPS", "Leather Scraps"),
      LIVING_FIRE = createItem(Items.BLAZE_POWDER, "LIVING_FIRE", "Living Fire"),
      LOBSTER_SOUL = createItem(Items.LAPIS_LAZULI, "LOBSTER_SOUL", "Lobster Soul"),
      LUMBERJACK_BOOTS = createItem(Items.LEATHER_BOOTS, "LUMBERJACK_BOOTS", "Lumberjack Boots"),
      LUMBERJACK_BOOTS_1 = createItem(Items.LEATHER_BOOTS, "LUMBERJACK_BOOTS_1", "Lumberjack Boots 1"),
      LUMBERJACK_BOOTS_2 = createItem(Items.LEATHER_BOOTS, "LUMBERJACK_BOOTS_2", "Lumberjack Boots 2"),
      LUMBERJACK_BOOTS_3 = createItem(Items.LEATHER_BOOTS, "LUMBERJACK_BOOTS_3", "Lumberjack Boots 3"),
      LUMBERJACK_BOOTS_4 = createItem(Items.LEATHER_BOOTS, "LUMBERJACK_BOOTS_4", "Lumberjack Boots 4"),
      LUMBERJACK_BOOTS_5 = createItem(Items.LEATHER_BOOTS, "LUMBERJACK_BOOTS_5", "Lumberjack Boots 5"),
      LUMBERJACK_CHESTPLATE = createItem(Items.LEATHER_CHESTPLATE, "LUMBERJACK_CHESTPLATE", "Lumberjack Chestplate"),
      LUMBERJACK_CHESTPLATE_1 = createItem(Items.LEATHER_CHESTPLATE, "LUMBERJACK_CHESTPLATE_1",
          "Lumberjack Chestplate 1"),
      LUMBERJACK_CHESTPLATE_2 = createItem(Items.LEATHER_CHESTPLATE, "LUMBERJACK_CHESTPLATE_2",
          "Lumberjack Chestplate 2"),
      LUMBERJACK_CHESTPLATE_3 = createItem(Items.LEATHER_CHESTPLATE, "LUMBERJACK_CHESTPLATE_3",
          "Lumberjack Chestplate 3"),
      LUMBERJACK_CHESTPLATE_4 = createItem(Items.LEATHER_CHESTPLATE, "LUMBERJACK_CHESTPLATE_4",
          "Lumberjack Chestplate 4"),
      LUMBERJACK_CHESTPLATE_5 = createItem(Items.LEATHER_CHESTPLATE, "LUMBERJACK_CHESTPLATE_5",
          "Lumberjack Chestplate 5"),
      LUMBERJACK_HELMET = createItem(Items.LEATHER_HELMET, "LUMBERJACK_HELMET", "Lumberjack Helmet"),
      LUMBERJACK_HELMET_1 = createItem(Items.LEATHER_HELMET, "LUMBERJACK_HELMET_1", "Lumberjack Helmet 1"),
      LUMBERJACK_HELMET_2 = createItem(Items.LEATHER_HELMET, "LUMBERJACK_HELMET_2", "Lumberjack Helmet 2"),
      LUMBERJACK_HELMET_3 = createItem(Items.LEATHER_HELMET, "LUMBERJACK_HELMET_3", "Lumberjack Helmet 3"),
      LUMBERJACK_HELMET_4 = createItem(Items.LEATHER_HELMET, "LUMBERJACK_HELMET_4", "Lumberjack Helmet 4"),
      LUMBERJACK_HELMET_5 = createItem(Items.LEATHER_HELMET, "LUMBERJACK_HELMET_5", "Lumberjack Helmet 5"),
      LUMBERJACK_LEGGINGS = createItem(Items.LEATHER_LEGGINGS, "LUMBERJACK_LEGGINGS", "Lumberjack Leggings"),
      LUMBERJACK_LEGGINGS_1 = createItem(Items.LEATHER_LEGGINGS, "LUMBERJACK_LEGGINGS_1", "Lumberjack Leggings 1"),
      LUMBERJACK_LEGGINGS_2 = createItem(Items.LEATHER_LEGGINGS, "LUMBERJACK_LEGGINGS_2", "Lumberjack Leggings 2"),
      LUMBERJACK_LEGGINGS_3 = createItem(Items.LEATHER_LEGGINGS, "LUMBERJACK_LEGGINGS_3", "Lumberjack Leggings 3"),
      LUMBERJACK_LEGGINGS_4 = createItem(Items.LEATHER_LEGGINGS, "LUMBERJACK_LEGGINGS_4", "Lumberjack Leggings 4"),
      LUMBERJACK_LEGGINGS_5 = createItem(Items.LEATHER_LEGGINGS, "LUMBERJACK_LEGGINGS_5", "Lumberjack Leggings 5"),
      LURE_EVERBUBBLING = createItem(Items.BLAZE_ROD, "LURE_EVERBUBBLING", "Lure Everbubbling"),
      MAGISTEEL_AXE = createItem(Items.NETHERITE_AXE, "MAGISTEEL_AXE", "Magisteel Axe"),
      MAGISTEEL_FISHINGPOLE = createItem(Items.FISHING_ROD, "MAGISTEEL_FISHINGPOLE", "Magisteel Fishingpole"),
      MAGISTEEL_HOE = createItem(Items.NETHERITE_HOE, "MAGISTEEL_HOE", "Magisteel Hoe"),
      MAGISTEEL_INGOT = createItem(Items.NETHERITE_INGOT, "MAGISTEEL_INGOT", "Magisteel Ingot"),
      MAGISTEEL_PICKAXE = createItem(Items.NETHERITE_PICKAXE, "MAGISTEEL_PICKAXE", "Magisteel Pickaxe"),
      MAGISTEEL_SHOVEL = createItem(Items.NETHERITE_SHOVEL, "MAGISTEEL_SHOVEL", "Magisteel Shovel"),
      MEAT_BROTH = createItem(Items.POTION, "MEAT_BROTH", "Meat Broth"),
      MEGA_MUSHROOM = createItem(Items.RED_MUSHROOM, "MEGA_MUSHROOM", "Mega Mushroom"),
      METEOR_SHARD = createItem(Items.NETHER_STAR, "METEOR_SHARD", "Meteor Shard"),
      MINER_BOOTS = createItem(Items.LEATHER_BOOTS, "MINER_BOOTS", "Miner Boots"),
      MINER_BOOTS_1 = createItem(Items.LEATHER_BOOTS, "MINER_BOOTS_1", "Miner Boots 1"),
      MINER_BOOTS_2 = createItem(Items.LEATHER_BOOTS, "MINER_BOOTS_2", "Miner Boots 2"),
      MINER_BOOTS_3 = createItem(Items.LEATHER_BOOTS, "MINER_BOOTS_3", "Miner Boots 3"),
      MINER_BOOTS_4 = createItem(Items.LEATHER_BOOTS, "MINER_BOOTS_4", "Miner Boots 4"),
      MINER_BOOTS_5 = createItem(Items.LEATHER_BOOTS, "MINER_BOOTS_5", "Miner Boots 5"),
      MINER_CHESTPLATE = createItem(Items.LEATHER_CHESTPLATE, "MINER_CHESTPLATE", "Miner Chestplate"),
      MINER_CHESTPLATE_1 = createItem(Items.LEATHER_CHESTPLATE, "MINER_CHESTPLATE_1", "Miner Chestplate 1"),
      MINER_CHESTPLATE_2 = createItem(Items.LEATHER_CHESTPLATE, "MINER_CHESTPLATE_2", "Miner Chestplate 2"),
      MINER_CHESTPLATE_3 = createItem(Items.LEATHER_CHESTPLATE, "MINER_CHESTPLATE_3", "Miner Chestplate 3"),
      MINER_CHESTPLATE_4 = createItem(Items.LEATHER_CHESTPLATE, "MINER_CHESTPLATE_4", "Miner Chestplate 4"),
      MINER_CHESTPLATE_5 = createItem(Items.LEATHER_CHESTPLATE, "MINER_CHESTPLATE_5", "Miner Chestplate 5"),
      MINER_HELMET = createItem(Items.LEATHER_HELMET, "MINER_HELMET", "Miner Helmet"),
      MINER_HELMET_1 = createItem(Items.LEATHER_HELMET, "MINER_HELMET_1", "Miner Helmet 1"),
      MINER_HELMET_2 = createItem(Items.LEATHER_HELMET, "MINER_HELMET_2", "Miner Helmet 2"),
      MINER_HELMET_3 = createItem(Items.LEATHER_HELMET, "MINER_HELMET_3", "Miner Helmet 3"),
      MINER_HELMET_4 = createItem(Items.LEATHER_HELMET, "MINER_HELMET_4", "Miner Helmet 4"),
      MINER_HELMET_5 = createItem(Items.LEATHER_HELMET, "MINER_HELMET_5", "Miner Helmet 5"),
      MINER_LEGGINGS = createItem(Items.LEATHER_LEGGINGS, "MINER_LEGGINGS", "Miner Leggings"),
      MINER_LEGGINGS_1 = createItem(Items.LEATHER_LEGGINGS, "MINER_LEGGINGS_1", "Miner Leggings 1"),
      MINER_LEGGINGS_2 = createItem(Items.LEATHER_LEGGINGS, "MINER_LEGGINGS_2", "Miner Leggings 2"),
      MINER_LEGGINGS_3 = createItem(Items.LEATHER_LEGGINGS, "MINER_LEGGINGS_3", "Miner Leggings 3"),
      MINER_LEGGINGS_4 = createItem(Items.LEATHER_LEGGINGS, "MINER_LEGGINGS_4", "Miner Leggings 4"),
      MINER_LEGGINGS_5 = createItem(Items.LEATHER_LEGGINGS, "MINER_LEGGINGS_5", "Miner Leggings 5"),
      MINI_MUSHROOM = createItem(Items.BROWN_MUSHROOM, "MINI_MUSHROOM", "Mini Mushroom"),
      MYTHRIL_BOOTS = createItem(Items.CHAINMAIL_BOOTS, "MYTHRIL_BOOTS", "Mythril Boots"),
      MYTHRIL_CHESTPLATE = createItem(Items.CHAINMAIL_CHESTPLATE, "MYTHRIL_CHESTPLATE", "Mythril Chestplate"),
      MYTHRIL_HELMET = createItem(Items.CHAINMAIL_HELMET, "MYTHRIL_HELMET", "Mythril Helmet"),
      MYTHRIL_INGOT = createItem(Items.IRON_INGOT, "MYTHRIL_INGOT", "Mythril Ingot"),
      MYTHRIL_LEGGINGS = createItem(Items.CHAINMAIL_LEGGINGS, "MYTHRIL_LEGGINGS", "Mythril Leggings"),
      MYTHRIL_SCRAP = createItem(Items.NETHERITE_SCRAP, "MYTHRIL_SCRAP", "Mythril Scrap"),
      NECRONOMICON = createItem(Items.BOOK, "NECRONOMICON", "Necronomicon"),
      NUTMEG = createItem(Items.COCOA_BEANS, "NUTMEG", "Nutmeg"),
      OLD_STONKS = createItem(Items.NETHERITE_SCRAP, "OLD_STONKS", "Old Stonks"),
      ONION_AXE = createItem(Items.WOODEN_AXE, "ONION_AXE", "Onion Axe"),
      ONION_BOOTS = createItem(Items.LEATHER_BOOTS, "ONION_BOOTS", "Onion Boots"),
      ONION_CHESTPLATE = createItem(Items.LEATHER_CHESTPLATE, "ONION_CHESTPLATE", "Onion Chestplate"),
      ONION_HELMET = createItem(Items.LEATHER_HELMET, "ONION_HELMET", "Onion Helmet"),
      ONION_LEGGINGS = createItem(Items.LEATHER_LEGGINGS, "ONION_LEGGINGS", "Onion Leggings"),
      ONION_PICKAXE = createItem(Items.WOODEN_PICKAXE, "ONION_PICKAXE", "Onion Pickaxe"),
      ONION_SHIELD = createItem(Items.WHITE_DYE, "ONION_SHIELD", "Onion Shield"),
      ONION_SWORD = createItem(Items.WOODEN_SWORD, "ONION_SWORD", "Onion Sword"),
      PAINTED_EGG = createItem(Items.PUFFERFISH, "PAINTED_EGG", "Painted Egg"),
      PEPPER = createItem(Items.GUNPOWDER, "PEPPER", "Pepper"),
      PERFECT_SPECIMEN = createItem(Items.ALLIUM, "PERFECT_SPECIMEN", "Perfect Specimen"),
      PICKLED_PHALANGES = createItem(Items.POTION, "PICKLED_PHALANGES", "Pickled Phalanges"),
      PIE_ALLBERRY = createItem(Items.PUMPKIN_PIE, "PIE_ALLBERRY", "Pie Allberry"),
      PIE_GLOWBERRY = createItem(Items.PUMPKIN_PIE, "PIE_GLOWBERRY", "Pie Glowberry"),
      PIE_JACKOLANTERN = createItem(Items.PUMPKIN_PIE, "PIE_JACKOLANTERN", "Pie Jackolantern"),
      PIE_MEAT = createItem(Items.PUMPKIN_PIE, "PIE_MEAT", "Pie Meat"),
      PIE_PUMPKIN = createItem(Items.PUMPKIN_PIE, "PIE_PUMPKIN", "Pie Pumpkin"),
      PIE_STARGAZY = createItem(Items.PUMPKIN_PIE, "PIE_STARGAZY", "Pie Stargazy"),
      PIE_SWEETBERRY = createItem(Items.PUMPKIN_PIE, "PIE_SWEETBERRY", "Pie Sweetberry"),
      PIGGLY_WIGGLY_BOW = createItem(Items.BOW, "PIGGLY_WIGGLY_BOW", "Piggly Wiggly Bow"),
      PLATINUM_COIN = createItem(Items.IRON_NUGGET, "PLATINUM_COIN", "Platinum Coin"),
      POLAR_BOOTS_2022 = createItem(Items.DIAMOND_BOOTS, "POLAR_BOOTS_2022", "Polar Boots 2022"),
      POLAR_CHESTPLATE_2022 = createItem(Items.DIAMOND_CHESTPLATE, "POLAR_CHESTPLATE_2022", "Polar Chestplate 2022"),
      POLAR_HELMET_2022 = createItem(Items.DIAMOND_HELMET, "POLAR_HELMET_2022", "Polar Helmet 2022"),
      POLAR_LEGGINGS_2022 = createItem(Items.DIAMOND_LEGGINGS, "POLAR_LEGGINGS_2022", "Polar Leggings 2022"),
      POTATOES_AND_GOLDEN_GRAVY = createItem(Items.BAKED_POTATO, "POTATOES_AND_GOLDEN_GRAVY",
          "Potatoes And Golden Gravy"),
      POTATOES_AND_GRAVY = createItem(Items.BAKED_POTATO, "POTATOES_AND_GRAVY", "Potatoes And Gravy"),
      POTATOES_AND_GRAVY_ANIMATED = createItem(Items.BAKED_POTATO, "POTATOES_AND_GRAVY_ANIMATED",
          "Potatoes And Gravy Animated"),
      POTATOES_AND_SENTIENT_GRAVY = createItem(Items.BAKED_POTATO, "POTATOES_AND_SENTIENT_GRAVY",
          "Potatoes And Sentient Gravy"),
      PRETTY_SHELL = createItem(Items.NAUTILUS_SHELL, "PRETTY_SHELL", "Pretty Shell"),
      PRISTINE_CORE = createItem(Items.SPRUCE_LOG, "PRISTINE_CORE", "Pristine Core"),
      PRISTINE_HIDE = createItem(Items.LEATHER, "PRISTINE_HIDE", "Pristine Hide"),
      PRISTINE_STONE = createItem(Items.FIREWORK_STAR, "PRISTINE_STONE", "Pristine Stone"),
      PRISTINE_WOOD = createItem(Items.BRICK, "PRISTINE_WOOD", "Pristine Wood"),
      PUMPKIN_BLADE = createItem(Items.NETHERITE_SWORD, "PUMPKIN_BLADE", "Pumpkin Blade"),
      PUMPKIN_BOOTS = createItem(Items.NETHERITE_BOOTS, "PUMPKIN_BOOTS", "Pumpkin Boots"),
      PUMPKIN_CHESTPLATE = createItem(Items.NETHERITE_CHESTPLATE, "PUMPKIN_CHESTPLATE", "Pumpkin Chestplate"),
      PUMPKIN_HELMET = createItem(Items.NETHERITE_HELMET, "PUMPKIN_HELMET", "Pumpkin Helmet"),
      PUMPKIN_LEGGINGS = createItem(Items.NETHERITE_LEGGINGS, "PUMPKIN_LEGGINGS", "Pumpkin Leggings"),
      QUIVER_CRYSTALLINE = createItem(Items.ARROW, "QUIVER_CRYSTALLINE", "Quiver Crystalline"),
      QUIVER_EXPLOSIVE = createItem(Items.ARROW, "QUIVER_EXPLOSIVE", "Quiver Explosive"),
      QUIVER_FIRE = createItem(Items.ARROW, "QUIVER_FIRE", "Quiver Fire"),
      QUIVER_FLINT = createItem(Items.ARROW, "QUIVER_FLINT", "Quiver Flint"),
      QUIVER_GREASY = createItem(Items.ARROW, "QUIVER_GREASY", "Quiver Greasy"),
      QUIVER_POISON = createItem(Items.ARROW, "QUIVER_POISON", "Quiver Poison"),
      QUIVER_SATET = createItem(Items.ARROW, "QUIVER_SATET", "Quiver Satet"),
      QUIVER_SLOW = createItem(Items.ARROW, "QUIVER_SLOW", "Quiver Slow"),
      QUIVER_SPARKING = createItem(Items.ARROW, "QUIVER_SPARKING", "Quiver Sparking"),
      QUIVER_UNSETTLING = createItem(Items.ARROW, "QUIVER_UNSETTLING", "Quiver Unsettling"),
      QUIVER_VOLCANIC = createItem(Items.ARROW, "QUIVER_VOLCANIC", "Quiver Volcanic"),
      RAID_CRATE_KROGNARS = createItem(Items.BARREL, "RAID_CRATE_KROGNARS", "Raid Crate Krognars"),
      RAID_CRATE_NEITH = createItem(Items.BARREL, "RAID_CRATE_NEITH", "Raid Crate Neith"),
      RAID_CRATE_ROTTEN = createItem(Items.BARREL, "RAID_CRATE_ROTTEN", "Raid Crate Rotten"),
      RAID_CRATE_SUNKEN = createItem(Items.BARREL, "RAID_CRATE_SUNKEN", "Raid Crate Sunken"),
      RAID_GUIDE_KROGNARS = createItem(Items.WRITTEN_BOOK, "RAID_GUIDE_KROGNARS", "Raid Guide Krognars"),
      RAID_GUIDE_ROTTEN = createItem(Items.WRITTEN_BOOK, "RAID_GUIDE_ROTTEN", "Raid Guide Rotten"),
      RAID_GUIDE_SUNKEN = createItem(Items.WRITTEN_BOOK, "RAID_GUIDE_SUNKEN", "Raid Guide Sunken"),
      RAW_GINGER = createItem(Items.POTATO, "RAW_GINGER", "Raw Ginger"),
      RAW_VEGGIE_SALAD = createItem(Items.RABBIT_STEW, "RAW_VEGGIE_SALAD", "Raw Veggie Salad"),
      RECIPE_BACON_AND_EGGS = createItem(Items.BOOK, "RECIPE_BACON_AND_EGGS", "Recipe Bacon And Eggs"),
      RECIPE_CANDYFISH = createItem(Items.BOOK, "RECIPE_CANDYFISH", "Recipe Candyfish"),
      RECIPE_CANDY_CORN = createItem(Items.BOOK, "RECIPE_CANDY_CORN", "Recipe Candy Corn"),
      RECIPE_CHOCOLATE_RABBIT = createItem(Items.BOOK, "RECIPE_CHOCOLATE_RABBIT", "Recipe Chocolate Rabbit"),
      RECIPE_COOKIE_GINGERBREAD = createItem(Items.BOOK, "RECIPE_COOKIE_GINGERBREAD", "Recipe Cookie Gingerbread"),
      RECIPE_EASTER_LAMB = createItem(Items.BOOK, "RECIPE_EASTER_LAMB", "Recipe Easter Lamb"),
      RECIPE_EGGNOG = createItem(Items.BOOK, "RECIPE_EGGNOG", "Recipe Eggnog"),
      RECIPE_HOT_CHOCOLATE = createItem(Items.BOOK, "RECIPE_HOT_CHOCOLATE", "Recipe Hot Chocolate"),
      RECIPE_HOT_CROSS_BUN = createItem(Items.BOOK, "RECIPE_HOT_CROSS_BUN", "Recipe Hot Cross Bun"),
      RECIPE_PAINTED_EGG = createItem(Items.BOOK, "RECIPE_PAINTED_EGG", "Recipe Painted Egg"),
      RECIPE_PICKLED_PHALANGES = createItem(Items.BOOK, "RECIPE_PICKLED_PHALANGES", "Recipe Pickled Phalanges"),
      RECIPE_PIE_JACKOLANTERN = createItem(Items.BOOK, "RECIPE_PIE_JACKOLANTERN", "Recipe Pie Jackolantern"),
      RECIPE_PIE_MEAT = createItem(Items.BOOK, "RECIPE_PIE_MEAT", "Recipe Pie Meat"),
      RECIPE_SPICED_SLUGS = createItem(Items.BOOK, "RECIPE_SPICED_SLUGS", "Recipe Spiced Slugs"),
      RECIPE_TOME_ACOLYTE_BOOTS = createItem(Items.BOOK, "RECIPE_TOME_ACOLYTE_BOOTS", "Recipe Tome Acolyte Boots"),
      RECIPE_TOME_ACOLYTE_CHESTPLATE = createItem(Items.BOOK, "RECIPE_TOME_ACOLYTE_CHESTPLATE",
          "Recipe Tome Acolyte Chestplate"),
      RECIPE_TOME_ACOLYTE_HELMET = createItem(Items.BOOK, "RECIPE_TOME_ACOLYTE_HELMET", "Recipe Tome Acolyte Helmet"),
      RECIPE_TOME_ACOLYTE_LEGGINGS = createItem(Items.BOOK, "RECIPE_TOME_ACOLYTE_LEGGINGS",
          "Recipe Tome Acolyte Leggings"),
      RECIPE_TOME_BLOODSNOUT_HEALER_BOOTS = createItem(Items.BOOK, "RECIPE_TOME_BLOODSNOUT_HEALER_BOOTS",
          "Recipe Tome Bloodsnout Healer Boots"),
      RECIPE_TOME_BLOODSNOUT_HEALER_CHESTPLATE = createItem(Items.BOOK, "RECIPE_TOME_BLOODSNOUT_HEALER_CHESTPLATE",
          "Recipe Tome Bloodsnout Healer Chestplate"),
      RECIPE_TOME_BLOODSNOUT_HEALER_HELMET = createItem(Items.BOOK, "RECIPE_TOME_BLOODSNOUT_HEALER_HELMET",
          "Recipe Tome Bloodsnout Healer Helmet"),
      RECIPE_TOME_BLOODSNOUT_HEALER_LEGGINGS = createItem(Items.BOOK, "RECIPE_TOME_BLOODSNOUT_HEALER_LEGGINGS",
          "Recipe Tome Bloodsnout Healer Leggings"),
      RECIPE_TOME_BLOODSNOUT_SLAYER_BOOTS = createItem(Items.BOOK, "RECIPE_TOME_BLOODSNOUT_SLAYER_BOOTS",
          "Recipe Tome Bloodsnout Slayer Boots"),
      RECIPE_TOME_BLOODSNOUT_SLAYER_CHESTPLATE = createItem(Items.BOOK, "RECIPE_TOME_BLOODSNOUT_SLAYER_CHESTPLATE",
          "Recipe Tome Bloodsnout Slayer Chestplate"),
      RECIPE_TOME_BLOODSNOUT_SLAYER_HELMET = createItem(Items.BOOK, "RECIPE_TOME_BLOODSNOUT_SLAYER_HELMET",
          "Recipe Tome Bloodsnout Slayer Helmet"),
      RECIPE_TOME_BLOODSNOUT_SLAYER_LEGGINGS = createItem(Items.BOOK, "RECIPE_TOME_BLOODSNOUT_SLAYER_LEGGINGS",
          "Recipe Tome Bloodsnout Slayer Leggings"),
      RECIPE_TOME_COLLAPSING_EARTH_3 = createItem(Items.BOOK, "RECIPE_TOME_COLLAPSING_EARTH_3",
          "Recipe Tome Collapsing Earth 3"),
      RECIPE_TOME_COLLAPSING_EARTH_4 = createItem(Items.BOOK, "RECIPE_TOME_COLLAPSING_EARTH_4",
          "Recipe Tome Collapsing Earth 4"),
      RECIPE_TOME_COLLAPSING_EARTH_5 = createItem(Items.BOOK, "RECIPE_TOME_COLLAPSING_EARTH_5",
          "Recipe Tome Collapsing Earth 5"),
      RECIPE_TOME_COLLAPSING_EARTH_6 = createItem(Items.BOOK, "RECIPE_TOME_COLLAPSING_EARTH_6",
          "Recipe Tome Collapsing Earth 6"),
      RECIPE_TOME_CORRUPTION_3 = createItem(Items.BOOK, "RECIPE_TOME_CORRUPTION_3", "Recipe Tome Corruption 3"),
      RECIPE_TOME_CORRUPTION_4 = createItem(Items.BOOK, "RECIPE_TOME_CORRUPTION_4", "Recipe Tome Corruption 4"),
      RECIPE_TOME_CORRUPTION_5 = createItem(Items.BOOK, "RECIPE_TOME_CORRUPTION_5", "Recipe Tome Corruption 5"),
      RECIPE_TOME_CORRUPTION_6 = createItem(Items.BOOK, "RECIPE_TOME_CORRUPTION_6", "Recipe Tome Corruption 6"),
      RECIPE_TOME_FIREBOLT_3 = createItem(Items.BOOK, "RECIPE_TOME_FIREBOLT_3", "Recipe Tome Firebolt 3"),
      RECIPE_TOME_FIREBOLT_4 = createItem(Items.BOOK, "RECIPE_TOME_FIREBOLT_4", "Recipe Tome Firebolt 4"),
      RECIPE_TOME_FIREBOLT_5 = createItem(Items.BOOK, "RECIPE_TOME_FIREBOLT_5", "Recipe Tome Firebolt 5"),
      RECIPE_TOME_FIREBOLT_6 = createItem(Items.BOOK, "RECIPE_TOME_FIREBOLT_6", "Recipe Tome Firebolt 6"),
      RECIPE_TOME_FLASH_HEAL_3 = createItem(Items.BOOK, "RECIPE_TOME_FLASH_HEAL_3", "Recipe Tome Flash Heal 3"),
      RECIPE_TOME_FLASH_HEAL_4 = createItem(Items.BOOK, "RECIPE_TOME_FLASH_HEAL_4", "Recipe Tome Flash Heal 4"),
      RECIPE_TOME_FLASH_HEAL_5 = createItem(Items.BOOK, "RECIPE_TOME_FLASH_HEAL_5", "Recipe Tome Flash Heal 5"),
      RECIPE_TOME_FLASH_HEAL_6 = createItem(Items.BOOK, "RECIPE_TOME_FLASH_HEAL_6", "Recipe Tome Flash Heal 6"),
      RECIPE_TOME_FROSTBOLT_3 = createItem(Items.BOOK, "RECIPE_TOME_FROSTBOLT_3", "Recipe Tome Frostbolt 3"),
      RECIPE_TOME_FROSTBOLT_4 = createItem(Items.BOOK, "RECIPE_TOME_FROSTBOLT_4", "Recipe Tome Frostbolt 4"),
      RECIPE_TOME_FROSTBOLT_5 = createItem(Items.BOOK, "RECIPE_TOME_FROSTBOLT_5", "Recipe Tome Frostbolt 5"),
      RECIPE_TOME_FROSTBOLT_6 = createItem(Items.BOOK, "RECIPE_TOME_FROSTBOLT_6", "Recipe Tome Frostbolt 6"),
      RECIPE_TOME_IMPLEMENT_BRAND = createItem(Items.BOOK, "RECIPE_TOME_IMPLEMENT_BRAND",
          "Recipe Tome Implement Brand"),
      RECIPE_TOME_IMPLEMENT_CALLER = createItem(Items.BOOK, "RECIPE_TOME_IMPLEMENT_CALLER",
          "Recipe Tome Implement Caller"),
      RECIPE_TOME_IMPLEMENT_HEKA = createItem(Items.BOOK, "RECIPE_TOME_IMPLEMENT_HEKA", "Recipe Tome Implement Heka"),
      RECIPE_TOME_LIFE_DRAIN_3 = createItem(Items.BOOK, "RECIPE_TOME_LIFE_DRAIN_3", "Recipe Tome Life Drain 3"),
      RECIPE_TOME_LIFE_DRAIN_4 = createItem(Items.BOOK, "RECIPE_TOME_LIFE_DRAIN_4", "Recipe Tome Life Drain 4"),
      RECIPE_TOME_LIFE_DRAIN_5 = createItem(Items.BOOK, "RECIPE_TOME_LIFE_DRAIN_5", "Recipe Tome Life Drain 5"),
      RECIPE_TOME_LIFE_DRAIN_6 = createItem(Items.BOOK, "RECIPE_TOME_LIFE_DRAIN_6", "Recipe Tome Life Drain 6"),
      RECIPE_TOME_MYTHRIL_BOOTS = createItem(Items.BOOK, "RECIPE_TOME_MYTHRIL_BOOTS", "Recipe Tome Mythril Boots"),
      RECIPE_TOME_MYTHRIL_CHESTPLATE = createItem(Items.BOOK, "RECIPE_TOME_MYTHRIL_CHESTPLATE",
          "Recipe Tome Mythril Chestplate"),
      RECIPE_TOME_MYTHRIL_HELMET = createItem(Items.BOOK, "RECIPE_TOME_MYTHRIL_HELMET", "Recipe Tome Mythril Helmet"),
      RECIPE_TOME_MYTHRIL_LEGGINGS = createItem(Items.BOOK, "RECIPE_TOME_MYTHRIL_LEGGINGS",
          "Recipe Tome Mythril Leggings"),
      RECIPE_TOME_PIGGLY_WIGGLY_BOW = createItem(Items.BOOK, "RECIPE_TOME_PIGGLY_WIGGLY_BOW",
          "Recipe Tome Piggly Wiggly Bow"),
      RECIPE_TOME_PRESSURE_WAVE_3 = createItem(Items.BOOK, "RECIPE_TOME_PRESSURE_WAVE_3",
          "Recipe Tome Pressure Wave 3"),
      RECIPE_TOME_PRESSURE_WAVE_4 = createItem(Items.BOOK, "RECIPE_TOME_PRESSURE_WAVE_4",
          "Recipe Tome Pressure Wave 4"),
      RECIPE_TOME_PRESSURE_WAVE_5 = createItem(Items.BOOK, "RECIPE_TOME_PRESSURE_WAVE_5",
          "Recipe Tome Pressure Wave 5"),
      RECIPE_TOME_PRESSURE_WAVE_6 = createItem(Items.BOOK, "RECIPE_TOME_PRESSURE_WAVE_6",
          "Recipe Tome Pressure Wave 6"),
      RECIPE_TOME_REGENERATION_3 = createItem(Items.BOOK, "RECIPE_TOME_REGENERATION_3", "Recipe Tome Regeneration 3"),
      RECIPE_TOME_REGENERATION_4 = createItem(Items.BOOK, "RECIPE_TOME_REGENERATION_4", "Recipe Tome Regeneration 4"),
      RECIPE_TOME_REGENERATION_5 = createItem(Items.BOOK, "RECIPE_TOME_REGENERATION_5", "Recipe Tome Regeneration 5"),
      RECIPE_TOME_REGENERATION_6 = createItem(Items.BOOK, "RECIPE_TOME_REGENERATION_6", "Recipe Tome Regeneration 6"),
      RECIPE_TOME_RING_OF_MERCY_3 = createItem(Items.BOOK, "RECIPE_TOME_RING_OF_MERCY_3",
          "Recipe Tome Ring Of Mercy 3"),
      RECIPE_TOME_RING_OF_MERCY_4 = createItem(Items.BOOK, "RECIPE_TOME_RING_OF_MERCY_4",
          "Recipe Tome Ring Of Mercy 4"),
      RECIPE_TOME_RING_OF_MERCY_5 = createItem(Items.BOOK, "RECIPE_TOME_RING_OF_MERCY_5",
          "Recipe Tome Ring Of Mercy 5"),
      RECIPE_TOME_RING_OF_MERCY_6 = createItem(Items.BOOK, "RECIPE_TOME_RING_OF_MERCY_6",
          "Recipe Tome Ring Of Mercy 6"),
      RECIPE_TOME_SANCTIFIED_BOOTS = createItem(Items.BOOK, "RECIPE_TOME_SANCTIFIED_BOOTS",
          "Recipe Tome Sanctified Boots"),
      RECIPE_TOME_SANCTIFIED_CHESTPLATE = createItem(Items.BOOK, "RECIPE_TOME_SANCTIFIED_CHESTPLATE",
          "Recipe Tome Sanctified Chestplate"),
      RECIPE_TOME_SANCTIFIED_HELMET = createItem(Items.BOOK, "RECIPE_TOME_SANCTIFIED_HELMET",
          "Recipe Tome Sanctified Helmet"),
      RECIPE_TOME_SANCTIFIED_LEGGINGS = createItem(Items.BOOK, "RECIPE_TOME_SANCTIFIED_LEGGINGS",
          "Recipe Tome Sanctified Leggings"),
      RECIPE_TOME_STEEL_BOOTS = createItem(Items.BOOK, "RECIPE_TOME_STEEL_BOOTS", "Recipe Tome Steel Boots"),
      RECIPE_TOME_STEEL_CHESTPLATE = createItem(Items.BOOK, "RECIPE_TOME_STEEL_CHESTPLATE",
          "Recipe Tome Steel Chestplate"),
      RECIPE_TOME_STEEL_HELMET = createItem(Items.BOOK, "RECIPE_TOME_STEEL_HELMET", "Recipe Tome Steel Helmet"),
      RECIPE_TOME_STEEL_LEGGINGS = createItem(Items.BOOK, "RECIPE_TOME_STEEL_LEGGINGS", "Recipe Tome Steel Leggings"),
      RECIPE_TOME_UNSETTLING_BOW = createItem(Items.BOOK, "RECIPE_TOME_UNSETTLING_BOW", "Recipe Tome Unsettling Bow"),
      REPAIR_PATCH_LEATHER = createItem(Items.DRIED_KELP, "REPAIR_PATCH_LEATHER", "Repair Patch Leather"),
      REPAIR_PATCH_ZOMBIE = createItem(Items.DRIED_KELP, "REPAIR_PATCH_ZOMBIE", "Repair Patch Zombie"),
      REPAIR_POWDER_ARCANE_COMMON = createItem(Items.REDSTONE, "REPAIR_POWDER_ARCANE_COMMON",
          "Repair Powder Arcane Common"),
      REPAIR_POWDER_ARCANE_EPIC = createItem(Items.REDSTONE, "REPAIR_POWDER_ARCANE_EPIC", "Repair Powder Arcane Epic"),
      REPAIR_POWDER_ARCANE_RARE = createItem(Items.REDSTONE, "REPAIR_POWDER_ARCANE_RARE", "Repair Powder Arcane Rare"),
      REPAIR_POWDER_ARCANE_UNCOMMON = createItem(Items.REDSTONE, "REPAIR_POWDER_ARCANE_UNCOMMON",
          "Repair Powder Arcane Uncommon"),
      REPAIR_POWDER_BASIC = createItem(Items.SUGAR, "REPAIR_POWDER_BASIC", "Repair Powder Basic"),
      REPAIR_POWDER_COMMON = createItem(Items.SUGAR, "REPAIR_POWDER_COMMON", "Repair Powder Common"),
      REPAIR_POWDER_EPIC = createItem(Items.SUGAR, "REPAIR_POWDER_EPIC", "Repair Powder Epic"),
      REPAIR_POWDER_EXOTIC = createItem(Items.SUGAR, "REPAIR_POWDER_EXOTIC", "Repair Powder Exotic"),
      REPAIR_POWDER_RARE = createItem(Items.SUGAR, "REPAIR_POWDER_RARE", "Repair Powder Rare"),
      REPAIR_POWDER_UNCOMMON = createItem(Items.SUGAR, "REPAIR_POWDER_UNCOMMON", "Repair Powder Uncommon"),
      REPLICATING_AMETHYST = createItem(Items.BUDDING_AMETHYST, "REPLICATING_AMETHYST", "Replicating Amethyst"),
      RIGHTEOUS_SOUL = createItem(Items.END_CRYSTAL, "RIGHTEOUS_SOUL", "Righteous Soul"),
      ROASTED_APPLE = createItem(Items.APPLE, "ROASTED_APPLE", "Roasted Apple"),
      ROASTED_BEETROOT = createItem(Items.BEETROOT, "ROASTED_BEETROOT", "Roasted Beetroot"),
      ROASTED_CARROT = createItem(Items.CARROT, "ROASTED_CARROT", "Roasted Carrot"),
      ROASTED_COOKIE = createItem(Items.COOKIE, "ROASTED_COOKIE", "Roasted Cookie"),
      ROASTED_GOLDEN_BEETROOT = createItem(Items.BEETROOT, "ROASTED_GOLDEN_BEETROOT", "Roasted Golden Beetroot"),
      ROASTED_GOLDEN_POTATO = createItem(Items.BAKED_POTATO, "ROASTED_GOLDEN_POTATO", "Roasted Golden Potato"),
      ROASTED_MUSHROOM = createItem(Items.BAKED_POTATO, "ROASTED_MUSHROOM", "Roasted Mushroom"),
      ROASTED_PLAIN_CHICKEN = createItem(Items.COOKED_CHICKEN, "ROASTED_PLAIN_CHICKEN", "Roasted Plain Chicken"),
      ROASTED_PLAIN_COD = createItem(Items.COOKED_COD, "ROASTED_PLAIN_COD", "Roasted Plain Cod"),
      ROASTED_PLAIN_MUTTON = createItem(Items.COOKED_MUTTON, "ROASTED_PLAIN_MUTTON", "Roasted Plain Mutton"),
      ROASTED_PLAIN_PORKCHOP = createItem(Items.COOKED_PORKCHOP, "ROASTED_PLAIN_PORKCHOP", "Roasted Plain Porkchop"),
      ROASTED_PLAIN_RABBIT = createItem(Items.COOKED_RABBIT, "ROASTED_PLAIN_RABBIT", "Roasted Plain Rabbit"),
      ROASTED_PLAIN_SALMON = createItem(Items.COOKED_SALMON, "ROASTED_PLAIN_SALMON", "Roasted Plain Salmon"),
      ROASTED_PLAIN_STEAK = createItem(Items.COOKED_BEEF, "ROASTED_PLAIN_STEAK", "Roasted Plain Steak"),
      ROASTED_PLAIN_TROPICAL_FISH = createItem(Items.COOKED_COD, "ROASTED_PLAIN_TROPICAL_FISH",
          "Roasted Plain Tropical Fish"),
      ROASTED_POTATO = createItem(Items.BAKED_POTATO, "ROASTED_POTATO", "Roasted Potato"),
      ROASTED_STUFFED_MUSHROOM = createItem(Items.BAKED_POTATO, "ROASTED_STUFFED_MUSHROOM", "Roasted Stuffed Mushroom"),
      ROSEBUD_SALAD = createItem(Items.RABBIT_STEW, "ROSEBUD_SALAD", "Rosebud Salad"),
      RUNE_CLARITY_1 = createItem(Items.TURTLE_EGG, "RUNECARVING_ADVANCEMENT_1", "Clarity - Rank 1"),
      RUNE_CLARITY_2 = createItem(Items.TURTLE_EGG, "RUNECARVING_ADVANCEMENT_2", "Clarity - Rank 2"),
      RUNE_CLARITY_3 = createItem(Items.TURTLE_EGG, "RUNECARVING_ADVANCEMENT_3", "Clarity - Rank 3"),
      RUNE_CLARITY_4 = createItem(Items.TURTLE_EGG, "RUNECARVING_ADVANCEMENT_4", "Clarity - Rank 4"),
      RUNE_CLARITY_5 = createItem(Items.TURTLE_EGG, "RUNECARVING_ADVANCEMENT_5", "Clarity - Rank 5"),
      RUNE_SERENITY_1 = createItem(Items.DIAMOND, "RUNECARVING_DEFENSE_1", "Serenity - Rank 1"),
      RUNE_SERENITY_2 = createItem(Items.DIAMOND, "RUNECARVING_DEFENSE_2", "Serenity - Rank 2"),
      RUNE_SERENITY_3 = createItem(Items.DIAMOND, "RUNECARVING_DEFENSE_3", "Serenity - Rank 3"),
      RUNE_SERENITY_4 = createItem(Items.DIAMOND, "RUNECARVING_DEFENSE_4", "Serenity - Rank 4"),
      RUNE_SERENITY_5 = createItem(Items.DIAMOND, "RUNECARVING_DEFENSE_5", "Serenity - Rank 5"),
      RUNE_MUDDLED_1 = createItem(Items.ENDER_PEARL, "RUNECARVING_MUDDLED_1", "Muddled - Rank 1"),
      RUNE_MUDDLED_2 = createItem(Items.ENDER_PEARL, "RUNECARVING_MUDDLED_2", "Muddled - Rank 2"),
      RUNE_MUDDLED_3 = createItem(Items.ENDER_PEARL, "RUNECARVING_MUDDLED_3", "Muddled - Rank 3"),
      RUNE_MUDDLED_4 = createItem(Items.ENDER_PEARL, "RUNECARVING_MUDDLED_4", "Muddled - Rank 4"),
      RUNE_MUDDLED_5 = createItem(Items.ENDER_PEARL, "RUNECARVING_MUDDLED_5", "Muddled - Rank 5"),
      RUNE_VIOLENCE_1 = createItem(Items.BLAZE_POWDER, "RUNECARVING_OFFENSE_1", "Violence - Rank 1"),
      RUNE_VIOLENCE_2 = createItem(Items.BLAZE_POWDER, "RUNECARVING_OFFENSE_2", "Violence - Rank 2"),
      RUNE_VIOLENCE_3 = createItem(Items.BLAZE_POWDER, "RUNECARVING_OFFENSE_3", "Violence - Rank 3"),
      RUNE_VIOLENCE_4 = createItem(Items.BLAZE_POWDER, "RUNECARVING_OFFENSE_4", "Violence - Rank 4"),
      RUNE_VIOLENCE_5 = createItem(Items.BLAZE_POWDER, "RUNECARVING_OFFENSE_5", "Violence - Rank 5"),
      RUNE_MURDER_1 = createItem(Items.SKELETON_SKULL, "RUNECARVING_PVP_1", "Murder - Rank 1"),
      RUNE_MURDER_2 = createItem(Items.SKELETON_SKULL, "RUNECARVING_PVP_2", "Murder - Rank 2"),
      RUNE_MURDER_3 = createItem(Items.SKELETON_SKULL, "RUNECARVING_PVP_3", "Murder - Rank 3"),
      RUNE_MURDER_4 = createItem(Items.SKELETON_SKULL, "RUNECARVING_PVP_4", "Murder - Rank 4"),
      RUNE_MURDER_5 = createItem(Items.SKELETON_SKULL, "RUNECARVING_PVP_5", "Murder - Rank 5"),
      RUNE_ERASER = createItem(Items.BLAZE_ROD, "RUNE_ERASER", "Rune Eraser"),
      ROTTEN_MAW_COMPASS = createItem(Items.STICK, "Rotten Maw - Compass", "Rotten maw - compass"),
      SALT = createItem(Items.SUGAR, "SALT", "Salt"),
      SALVAGE_KIT = createItem(Items.JUKEBOX, "SALVAGE_KIT", "Salvage Kit"),
      SANCTIFIED_BOOTS = createItem(Items.LEATHER_BOOTS, "SANCTIFIED_BOOTS", "Sanctified Boots"),
      SANCTIFIED_CHESTPLATE = createItem(Items.LEATHER_CHESTPLATE, "SANCTIFIED_CHESTPLATE", "Sanctified Chestplate"),
      SANCTIFIED_HELMET = createItem(Items.LEATHER_HELMET, "SANCTIFIED_HELMET", "Sanctified Helmet"),
      SANCTIFIED_LEGGINGS = createItem(Items.LEATHER_LEGGINGS, "SANCTIFIED_LEGGINGS", "Sanctified Leggings"),
      SANDY_HIDE = createItem(Items.LEATHER, "SANDY_HIDE", "Sandy Hide"),
      SATET_BOW = createItem(Items.BOW, "SATET_BOW", "Satet Bow"),
      SECRETS_ARCHAEOLOGY = createItem(Items.BOOK, "SECRETS_ARCHAEOLOGY", "Secrets Archaeology"),
      SECRETS_CLASS = createItem(Items.BOOK, "SECRETS_CLASS", "Secrets Class"),
      SECRETS_FISHING = createItem(Items.BOOK, "SECRETS_FISHING", "Secrets Fishing"),
      SECRETS_HERBALISM = createItem(Items.BOOK, "SECRETS_HERBALISM", "Secrets Herbalism"),
      SECRETS_LOGGING = createItem(Items.BOOK, "SECRETS_LOGGING", "Secrets Logging"),
      SECRETS_MINING = createItem(Items.BOOK, "SECRETS_MINING", "Secrets Mining"),
      SEE_BREATHER = createItem(Items.SEA_PICKLE, "SEE_BREATHER", "See Breather"),
      SENTIENT_BREAD = createItem(Items.BREAD, "SENTIENT_BREAD", "Sentient Bread"),
      SENTIENT_DOUGH = createItem(Items.CYAN_DYE, "SENTIENT_DOUGH", "Sentient Dough"),
      SENTIENT_FLOUR = createItem(Items.SUGAR, "SENTIENT_FLOUR", "Sentient Flour"),
      SENTIENT_GRAVY = createItem(Items.POTION, "SENTIENT_GRAVY", "Sentient Gravy"),
      SENTIENT_POTATOES_AND_SENTIENT_GRAVY = createItem(Items.BAKED_POTATO, "SENTIENT_POTATOES_AND_SENTIENT_GRAVY",
          "Sentient Potatoes And Sentient Gravy"),
      SENTIENT_POTATOES_AND_SENTIENT_GRAVY_ANIMATED = createItem(Items.BAKED_POTATO,
          "SENTIENT_POTATOES_AND_SENTIENT_GRAVY_ANIMATED", "Sentient Potatoes And Sentient Gravy Animated"),
      SENTIENT_WHEAT = createItem(Items.WHEAT, "SENTIENT_WHEAT", "Sentient Wheat"),
      SHELL_EVERBUBBLING = createItem(Items.NAUTILUS_SHELL, "SHELL_EVERBUBBLING", "Shell Everbubbling"),
      SHIMMERGLASS_AXE = createItem(Items.DIAMOND_AXE, "SHIMMERGLASS_AXE", "Shimmerglass Axe"),
      SHIMMERGLASS_FISHINGPOLE = createItem(Items.FISHING_ROD, "SHIMMERGLASS_FISHINGPOLE", "Shimmerglass Fishingpole"),
      SHIMMERGLASS_HOE = createItem(Items.DIAMOND_HOE, "SHIMMERGLASS_HOE", "Shimmerglass Hoe"),
      SHIMMERGLASS_PICKAXE = createItem(Items.DIAMOND_PICKAXE, "SHIMMERGLASS_PICKAXE", "Shimmerglass Pickaxe"),
      SHIMMERGLASS_SHOVEL = createItem(Items.DIAMOND_SHOVEL, "SHIMMERGLASS_SHOVEL", "Shimmerglass Shovel"),
      SILK_BOOTS = createItem(Items.LEATHER_BOOTS, "SILK_BOOTS", "Silk Boots"),
      SILK_CHESTPLATE = createItem(Items.LEATHER_CHESTPLATE, "SILK_CHESTPLATE", "Silk Chestplate"),
      SILK_HELMET = createItem(Items.LEATHER_HELMET, "SILK_HELMET", "Silk Helmet"),
      SILK_LEGGINGS = createItem(Items.LEATHER_LEGGINGS, "SILK_LEGGINGS", "Silk Leggings"),
      SKELETAL_BOW = createItem(Items.BOW, "SKELETAL_BOW", "Skeletal Bow"),
      SKYSTEEL_AXE = createItem(Items.IRON_AXE, "SKYSTEEL_AXE", "Skysteel Axe"),
      SKYSTEEL_FISHINGPOLE = createItem(Items.FISHING_ROD, "SKYSTEEL_FISHINGPOLE", "Skysteel Fishingpole"),
      SKYSTEEL_HOE = createItem(Items.IRON_HOE, "SKYSTEEL_HOE", "Skysteel Hoe"),
      SKYSTEEL_PICKAXE = createItem(Items.IRON_PICKAXE, "SKYSTEEL_PICKAXE", "Skysteel Pickaxe"),
      SKYSTEEL_SHOVEL = createItem(Items.IRON_SHOVEL, "SKYSTEEL_SHOVEL", "Skysteel Shovel"),
      SMOKED_APPLE = createItem(Items.APPLE, "SMOKED_APPLE", "Smoked Apple"),
      SMOKED_BEETROOT = createItem(Items.BEETROOT, "SMOKED_BEETROOT", "Smoked Beetroot"),
      SMOKED_CARROT = createItem(Items.CARROT, "SMOKED_CARROT", "Smoked Carrot"),
      SMOKED_COOKIE = createItem(Items.COOKIE, "SMOKED_COOKIE", "Smoked Cookie"),
      SMOKED_GOLDEN_BEETROOT = createItem(Items.BEETROOT, "SMOKED_GOLDEN_BEETROOT", "Smoked Golden Beetroot"),
      SMOKED_GOLDEN_POTATO = createItem(Items.BAKED_POTATO, "SMOKED_GOLDEN_POTATO", "Smoked Golden Potato"),
      SMOKED_MUSHROOM = createItem(Items.BAKED_POTATO, "SMOKED_MUSHROOM", "Smoked Mushroom"),
      SMOKED_PLAIN_CHICKEN = createItem(Items.COOKED_CHICKEN, "SMOKED_PLAIN_CHICKEN", "Smoked Plain Chicken"),
      SMOKED_PLAIN_COD = createItem(Items.COOKED_COD, "SMOKED_PLAIN_COD", "Smoked Plain Cod"),
      SMOKED_PLAIN_MUTTON = createItem(Items.COOKED_MUTTON, "SMOKED_PLAIN_MUTTON", "Smoked Plain Mutton"),
      SMOKED_PLAIN_PORKCHOP = createItem(Items.COOKED_PORKCHOP, "SMOKED_PLAIN_PORKCHOP", "Smoked Plain Porkchop"),
      SMOKED_PLAIN_RABBIT = createItem(Items.COOKED_RABBIT, "SMOKED_PLAIN_RABBIT", "Smoked Plain Rabbit"),
      SMOKED_PLAIN_SALMON = createItem(Items.COOKED_SALMON, "SMOKED_PLAIN_SALMON", "Smoked Plain Salmon"),
      SMOKED_PLAIN_STEAK = createItem(Items.COOKED_BEEF, "SMOKED_PLAIN_STEAK", "Smoked Plain Steak"),
      SMOKED_PLAIN_TROPICAL_FISH = createItem(Items.COOKED_COD, "SMOKED_PLAIN_TROPICAL_FISH",
          "Smoked Plain Tropical Fish"),
      SMOKED_POTATO = createItem(Items.BAKED_POTATO, "SMOKED_POTATO", "Smoked Potato"),
      SMOKED_STUFFED_MUSHROOM = createItem(Items.BAKED_POTATO, "SMOKED_STUFFED_MUSHROOM", "Smoked Stuffed Mushroom"),
      SMOOTHIE_STAR = createItem(Items.POTION, "SMOOTHIE_STAR", "Smoothie Star"),
      SOGGY_BOOK = createItem(Items.BOOK, "SOGGY_BOOK", "Soggy Book"),
      SOUL_CHARGE = createItem(Items.GLOWSTONE, "SOUL_CHARGE", "Soul Charge"),
      SOUL_FRAGMENT = createItem(Items.AMETHYST_SHARD, "SOUL_FRAGMENT", "Soul Fragment"),
      SOUL_SHARD = createItem(Items.AMETHYST_SHARD, "SOUL_SHARD", "Soul Shard"),
      SPARKING_SILK_BOOTS = createItem(Items.LEATHER_BOOTS, "SPARKING_SILK_BOOTS", "Sparking Silk Boots"),
      SPARKING_SILK_CHESTPLATE = createItem(Items.LEATHER_CHESTPLATE, "SPARKING_SILK_CHESTPLATE",
          "Sparking Silk Chestplate"),
      SPARKING_SILK_HELMET = createItem(Items.LEATHER_HELMET, "SPARKING_SILK_HELMET", "Sparking Silk Helmet"),
      SPARKING_SILK_LEGGINGS = createItem(Items.LEATHER_LEGGINGS, "SPARKING_SILK_LEGGINGS", "Sparking Silk Leggings"),
      SPICED_SLUGS = createItem(Items.POTION, "SPICED_SLUGS", "Spiced Slugs"),
      SPIRIT_ACACIA = createItem(Items.PHANTOM_MEMBRANE, "SPIRIT_ACACIA", "Spirit Acacia"),
      SPIRIT_BIRCH = createItem(Items.PHANTOM_MEMBRANE, "SPIRIT_BIRCH", "Spirit Birch"),
      SPIRIT_DARKOAK = createItem(Items.PHANTOM_MEMBRANE, "SPIRIT_DARKOAK", "Spirit Darkoak"),
      SPIRIT_JUNGLE = createItem(Items.PHANTOM_MEMBRANE, "SPIRIT_JUNGLE", "Spirit Jungle"),
      SPIRIT_OAK = createItem(Items.PHANTOM_MEMBRANE, "SPIRIT_OAK", "Spirit Oak"),
      SPIRIT_SPRUCE = createItem(Items.PHANTOM_MEMBRANE, "SPIRIT_SPRUCE", "Spirit Spruce"),
      STARTER_ARCHAEOLOGIST_CHISELED = createItem(Items.CHISELED_SANDSTONE, "STARTER_ARCHAEOLOGIST_CHISELED",
          "Starter Archaeologist Chiseled"),
      STARTER_ARCHAEOLOGIST_COMMONSHELL = createItem(Items.CHISELED_SANDSTONE, "STARTER_ARCHAEOLOGIST_COMMONSHELL",
          "Starter Archaeologist Commonshell"),
      STARTER_ARCHAEOLOGIST_FANCYSHELL = createItem(Items.CHISELED_SANDSTONE, "STARTER_ARCHAEOLOGIST_FANCYSHELL",
          "Starter Archaeologist Fancyshell"),
      STARTER_ARCHAEOLOGIST_PRETTYSHELL = createItem(Items.CHISELED_SANDSTONE, "STARTER_ARCHAEOLOGIST_PRETTYSHELL",
          "Starter Archaeologist Prettyshell"),
      STARTER_ARCHAEOLOGIST_SALT = createItem(Items.CHISELED_SANDSTONE, "STARTER_ARCHAEOLOGIST_SALT",
          "Starter Archaeologist Salt"),
      STARTER_BOTANIST_BEETROOT = createItem(Items.GREEN_DYE, "STARTER_BOTANIST_BEETROOT", "Starter Botanist Beetroot"),
      STARTER_BOTANIST_CARROT = createItem(Items.GREEN_DYE, "STARTER_BOTANIST_CARROT", "Starter Botanist Carrot"),
      STARTER_BOTANIST_PEPPER = createItem(Items.GREEN_DYE, "STARTER_BOTANIST_PEPPER", "Starter Botanist Pepper"),
      STARTER_BOTANIST_POTATO = createItem(Items.GREEN_DYE, "STARTER_BOTANIST_POTATO", "Starter Botanist Potato"),
      STARTER_BOTANIST_WHEAT = createItem(Items.GREEN_DYE, "STARTER_BOTANIST_WHEAT", "Starter Botanist Wheat"),
      STARTER_CHRISTMAS = createItem(Items.SNOW, "STARTER_CHRISTMAS", "Starter Christmas"),
      STARTER_FISHERMAN_COD = createItem(Items.PAPER, "STARTER_FISHERMAN_COD", "Starter Fisherman Cod"),
      STARTER_FISHERMAN_FROST = createItem(Items.PAPER, "STARTER_FISHERMAN_FROST", "Starter Fisherman Frost"),
      STARTER_FISHERMAN_PUFFER = createItem(Items.PAPER, "STARTER_FISHERMAN_PUFFER", "Starter Fisherman Puffer"),
      STARTER_FISHERMAN_SALMON = createItem(Items.PAPER, "STARTER_FISHERMAN_SALMON", "Starter Fisherman Salmon"),
      STARTER_FISHERMAN_TROPICAL = createItem(Items.PAPER, "STARTER_FISHERMAN_TROPICAL", "Starter Fisherman Tropical"),
      STARTER_FISHERMAN_WATER = createItem(Items.PAPER, "STARTER_FISHERMAN_WATER", "Starter Fisherman Water"),
      STARTER_HALLOWEEN = createItem(Items.JACK_O_LANTERN, "STARTER_HALLOWEEN", "Starter Halloween"),
      STARTER_HUNTER_OUTPOST_DESTROYED = createItem(Items.BARREL, "STARTER_HUNTER_OUTPOST_DESTROYED",
          "Starter Hunter Outpost Destroyed"),
      STARTER_HUNTER_PILLAGER = createItem(Items.BARREL, "STARTER_HUNTER_PILLAGER", "Starter Hunter Pillager"),
      STARTER_LUMBERJACK_ACACIA = createItem(Items.ACACIA_LOG, "STARTER_LUMBERJACK_ACACIA",
          "Starter Lumberjack Acacia"),
      STARTER_LUMBERJACK_BIRCH = createItem(Items.BIRCH_LOG, "STARTER_LUMBERJACK_BIRCH", "Starter Lumberjack Birch"),
      STARTER_LUMBERJACK_CHERRY = createItem(Items.CHERRY_LOG, "STARTER_LUMBERJACK_CHERRY",
          "Starter Lumberjack Cherry"),
      STARTER_LUMBERJACK_DARKOAK = createItem(Items.DARK_OAK_LOG, "STARTER_LUMBERJACK_DARKOAK",
          "Starter Lumberjack Darkoak"),
      STARTER_LUMBERJACK_JUNGLE = createItem(Items.JUNGLE_LOG, "STARTER_LUMBERJACK_JUNGLE",
          "Starter Lumberjack Jungle"),
      STARTER_LUMBERJACK_MANGROVE = createItem(Items.MANGROVE_LOG, "STARTER_LUMBERJACK_MANGROVE",
          "Starter Lumberjack Mangrove"),
      STARTER_LUMBERJACK_OAK = createItem(Items.OAK_LOG, "STARTER_LUMBERJACK_OAK", "Starter Lumberjack Oak"),
      STARTER_LUMBERJACK_SPRUCE = createItem(Items.SPRUCE_LOG, "STARTER_LUMBERJACK_SPRUCE",
          "Starter Lumberjack Spruce"),
      STARTER_MINER_COPPER = createItem(Items.CHARCOAL, "STARTER_MINER_COPPER", "Starter Miner Copper"),
      STARTER_MINER_EARTH = createItem(Items.CHARCOAL, "STARTER_MINER_EARTH", "Starter Miner Earth"),
      STARTER_MINER_GEODE = createItem(Items.CHARCOAL, "STARTER_MINER_GEODE", "Starter Miner Geode"),
      STARTER_MINER_IRON = createItem(Items.CHARCOAL, "STARTER_MINER_IRON", "Starter Miner Iron"),
      STARTER_MINER_LAPIS = createItem(Items.CHARCOAL, "STARTER_MINER_LAPIS", "Starter Miner Lapis"),
      STARTER_MINER_REDSTONE = createItem(Items.CHARCOAL, "STARTER_MINER_REDSTONE", "Starter Miner Redstone"),
      STARTER_MINER_SPARK = createItem(Items.CHARCOAL, "STARTER_MINER_SPARK", "Starter Miner Spark"),
      STARTER_RUNECARVER_CLARITY = createItem(Items.CHISELED_POLISHED_BLACKSTONE, "STARTER_RUNECARVER_CLARITY",
          "Starter Runecarver Clarity"),
      STARTER_RUNECARVER_MUDDLED = createItem(Items.CHISELED_POLISHED_BLACKSTONE, "STARTER_RUNECARVER_MUDDLED",
          "Starter Runecarver Muddled"),
      STARTER_RUNECARVER_SERENITY = createItem(Items.CHISELED_POLISHED_BLACKSTONE, "STARTER_RUNECARVER_SERENITY",
          "Starter Runecarver Serenity"),
      STARTER_RUNECARVER_VIOLENCE = createItem(Items.CHISELED_POLISHED_BLACKSTONE, "STARTER_RUNECARVER_VIOLENCE",
          "Starter Runecarver Violence"),
      STEEL_BOOTS = createItem(Items.IRON_BOOTS, "STEEL_BOOTS", "Steel Boots"),
      STEEL_CHESTPLATE = createItem(Items.IRON_CHESTPLATE, "STEEL_CHESTPLATE", "Steel Chestplate"),
      STEEL_HELMET = createItem(Items.IRON_HELMET, "STEEL_HELMET", "Steel Helmet"),
      STEEL_INGOT = createItem(Items.IRON_INGOT, "STEEL_INGOT", "Steel Ingot"),
      STEEL_LEGGINGS = createItem(Items.IRON_LEGGINGS, "STEEL_LEGGINGS", "Steel Leggings"),
      STEEL_SCRAP = createItem(Items.NETHERITE_SCRAP, "STEEL_SCRAP", "Steel Scrap"),
      STONE_BOOTS = createItem(Items.LEATHER_BOOTS, "STONE_BOOTS", "Stone Boots"),
      STONE_CHESTPLATE = createItem(Items.LEATHER_CHESTPLATE, "STONE_CHESTPLATE", "Stone Chestplate"),
      STONE_HELMET = createItem(Items.LEATHER_HELMET, "STONE_HELMET", "Stone Helmet"),
      STONE_LEGGINGS = createItem(Items.LEATHER_LEGGINGS, "STONE_LEGGINGS", "Stone Leggings"),
      STONE_SWORD = createItem(Items.STONE_SWORD, "STONE_SWORD", "Stone Sword"),
      STRONG_BOW = createItem(Items.BOW, "STRONG_BOW", "Strong Bow"),
      STRONG_FISHINGPOLE = createItem(Items.FISHING_ROD, "STRONG_FISHINGPOLE", "Strong Fishingpole"),
      STUFFED_MUSHROOM = createItem(Items.BAKED_POTATO, "STUFFED_MUSHROOM", "Stuffed Mushroom"),
      SUNKEN_CELLS_COMPASS = createItem(Items.STICK, "Sunken Cells - Compass", "Sunken cells - compass"),
      T1_RANDOM_COLLAPSING_EARTH = createItem(Items.BOOK, "T1_RANDOM_COLLAPSING_EARTH", "T1 Random Collapsing Earth"),
      T1_RANDOM_CORRUPTION = createItem(Items.BOOK, "T1_RANDOM_CORRUPTION", "T1 Random Corruption"),
      T1_RANDOM_FIREBOLT = createItem(Items.BOOK, "T1_RANDOM_FIREBOLT", "T1 Random Firebolt"),
      T1_RANDOM_FLASH_HEAL = createItem(Items.BOOK, "T1_RANDOM_FLASH_HEAL", "T1 Random Flash Heal"),
      T1_RANDOM_FROSTBOLT = createItem(Items.BOOK, "T1_RANDOM_FROSTBOLT", "T1 Random Frostbolt"),
      T1_RANDOM_LIFE_DRAIN = createItem(Items.BOOK, "T1_RANDOM_LIFE_DRAIN", "T1 Random Life Drain"),
      T1_RANDOM_PRESSURE_WAVE = createItem(Items.BOOK, "T1_RANDOM_PRESSURE_WAVE", "T1 Random Pressure Wave"),
      T1_RANDOM_REGENERATION = createItem(Items.BOOK, "T1_RANDOM_REGENERATION", "T1 Random Regeneration"),
      T1_RANDOM_RING_OF_MERCY = createItem(Items.BOOK, "T1_RANDOM_RING_OF_MERCY", "T1 Random Ring Of Mercy"),
      T2_RANDOM_COLLAPSING_EARTH = createItem(Items.BOOK, "T2_RANDOM_COLLAPSING_EARTH", "T2 Random Collapsing Earth"),
      T2_RANDOM_CORRUPTION = createItem(Items.BOOK, "T2_RANDOM_CORRUPTION", "T2 Random Corruption"),
      T2_RANDOM_FIREBOLT = createItem(Items.BOOK, "T2_RANDOM_FIREBOLT", "T2 Random Firebolt"),
      T2_RANDOM_FLASH_HEAL = createItem(Items.BOOK, "T2_RANDOM_FLASH_HEAL", "T2 Random Flash Heal"),
      T2_RANDOM_FROSTBOLT = createItem(Items.BOOK, "T2_RANDOM_FROSTBOLT", "T2 Random Frostbolt"),
      T2_RANDOM_LIFE_DRAIN = createItem(Items.BOOK, "T2_RANDOM_LIFE_DRAIN", "T2 Random Life Drain"),
      T2_RANDOM_PRESSURE_WAVE = createItem(Items.BOOK, "T2_RANDOM_PRESSURE_WAVE", "T2 Random Pressure Wave"),
      T2_RANDOM_REGENERATION = createItem(Items.BOOK, "T2_RANDOM_REGENERATION", "T2 Random Regeneration"),
      T2_RANDOM_RING_OF_MERCY = createItem(Items.BOOK, "T2_RANDOM_RING_OF_MERCY", "T2 Random Ring Of Mercy"),
      T3_RANDOM_COLLAPSING_EARTH = createItem(Items.BOOK, "T3_RANDOM_COLLAPSING_EARTH", "T3 Random Collapsing Earth"),
      T3_RANDOM_CORRUPTION = createItem(Items.BOOK, "T3_RANDOM_CORRUPTION", "T3 Random Corruption"),
      T3_RANDOM_FIREBOLT = createItem(Items.BOOK, "T3_RANDOM_FIREBOLT", "T3 Random Firebolt"),
      T3_RANDOM_FLASH_HEAL = createItem(Items.BOOK, "T3_RANDOM_FLASH_HEAL", "T3 Random Flash Heal"),
      T3_RANDOM_FROSTBOLT = createItem(Items.BOOK, "T3_RANDOM_FROSTBOLT", "T3 Random Frostbolt"),
      T3_RANDOM_LIFE_DRAIN = createItem(Items.BOOK, "T3_RANDOM_LIFE_DRAIN", "T3 Random Life Drain"),
      T3_RANDOM_PRESSURE_WAVE = createItem(Items.BOOK, "T3_RANDOM_PRESSURE_WAVE", "T3 Random Pressure Wave"),
      T3_RANDOM_REGENERATION = createItem(Items.BOOK, "T3_RANDOM_REGENERATION", "T3 Random Regeneration"),
      T3_RANDOM_RING_OF_MERCY = createItem(Items.BOOK, "T3_RANDOM_RING_OF_MERCY", "T3 Random Ring Of Mercy"),
      T4_RANDOM_BATTLETOTEM = createItem(Items.WEEPING_VINES, "T4_RANDOM_BATTLETOTEM", "T4 Random Battletotem"),
      T4_RANDOM_COLLAPSING_EARTH = createItem(Items.BOOK, "T4_RANDOM_COLLAPSING_EARTH", "T4 Random Collapsing Earth"),
      T4_RANDOM_CORRUPTION = createItem(Items.BOOK, "T4_RANDOM_CORRUPTION", "T4 Random Corruption"),
      T4_RANDOM_FIREBOLT = createItem(Items.BOOK, "T4_RANDOM_FIREBOLT", "T4 Random Firebolt"),
      T4_RANDOM_FLASH_HEAL = createItem(Items.BOOK, "T4_RANDOM_FLASH_HEAL", "T4 Random Flash Heal"),
      T4_RANDOM_FROSTBOLT = createItem(Items.BOOK, "T4_RANDOM_FROSTBOLT", "T4 Random Frostbolt"),
      T4_RANDOM_LIFE_DRAIN = createItem(Items.BOOK, "T4_RANDOM_LIFE_DRAIN", "T4 Random Life Drain"),
      T4_RANDOM_PRESSURE_WAVE = createItem(Items.BOOK, "T4_RANDOM_PRESSURE_WAVE", "T4 Random Pressure Wave"),
      T4_RANDOM_REGENERATION = createItem(Items.BOOK, "T4_RANDOM_REGENERATION", "T4 Random Regeneration"),
      T4_RANDOM_RING_OF_MERCY = createItem(Items.BOOK, "T4_RANDOM_RING_OF_MERCY", "T4 Random Ring Of Mercy"),
      T5_RANDOM_COLLAPSING_EARTH = createItem(Items.BOOK, "T5_RANDOM_COLLAPSING_EARTH", "T5 Random Collapsing Earth"),
      T5_RANDOM_CORRUPTION = createItem(Items.BOOK, "T5_RANDOM_CORRUPTION", "T5 Random Corruption"),
      T5_RANDOM_FIREBOLT = createItem(Items.BOOK, "T5_RANDOM_FIREBOLT", "T5 Random Firebolt"),
      T5_RANDOM_FLASH_HEAL = createItem(Items.BOOK, "T5_RANDOM_FLASH_HEAL", "T5 Random Flash Heal"),
      T5_RANDOM_FROSTBOLT = createItem(Items.BOOK, "T5_RANDOM_FROSTBOLT", "T5 Random Frostbolt"),
      T5_RANDOM_IMPLEMENT = createItem(Items.BREWING_STAND, "T5_RANDOM_IMPLEMENT", "T5 Random Implement"),
      T5_RANDOM_LIFE_DRAIN = createItem(Items.BOOK, "T5_RANDOM_LIFE_DRAIN", "T5 Random Life Drain"),
      T5_RANDOM_PRESSURE_WAVE = createItem(Items.BOOK, "T5_RANDOM_PRESSURE_WAVE", "T5 Random Pressure Wave"),
      T5_RANDOM_REGENERATION = createItem(Items.BOOK, "T5_RANDOM_REGENERATION", "T5 Random Regeneration"),
      T5_RANDOM_RING_OF_MERCY = createItem(Items.BOOK, "T5_RANDOM_RING_OF_MERCY", "T5 Random Ring Of Mercy"),
      T5_RANDOM_SPELLFOCUS = createItem(Items.BLAZE_POWDER, "T5_RANDOM_SPELLFOCUS", "T5 Random Spellfocus"),
      T6_RANDOM_COLLAPSING_EARTH = createItem(Items.BOOK, "T6_RANDOM_COLLAPSING_EARTH", "T6 Random Collapsing Earth"),
      T6_RANDOM_CORRUPTION = createItem(Items.BOOK, "T6_RANDOM_CORRUPTION", "T6 Random Corruption"),
      T6_RANDOM_FIREBOLT = createItem(Items.BOOK, "T6_RANDOM_FIREBOLT", "T6 Random Firebolt"),
      T6_RANDOM_FLASH_HEAL = createItem(Items.BOOK, "T6_RANDOM_FLASH_HEAL", "T6 Random Flash Heal"),
      T6_RANDOM_FROSTBOLT = createItem(Items.BOOK, "T6_RANDOM_FROSTBOLT", "T6 Random Frostbolt"),
      T6_RANDOM_LIFE_DRAIN = createItem(Items.BOOK, "T6_RANDOM_LIFE_DRAIN", "T6 Random Life Drain"),
      T6_RANDOM_PRESSURE_WAVE = createItem(Items.BOOK, "T6_RANDOM_PRESSURE_WAVE", "T6 Random Pressure Wave"),
      T6_RANDOM_REGENERATION = createItem(Items.BOOK, "T6_RANDOM_REGENERATION", "T6 Random Regeneration"),
      T6_RANDOM_RING_OF_MERCY = createItem(Items.BOOK, "T6_RANDOM_RING_OF_MERCY", "T6 Random Ring Of Mercy"),
      TAINTED_METAL = createItem(Items.NETHERITE_INGOT, "TAINTED_METAL", "Tainted Metal"),
      TASTY_MELON_POP = createItem(Items.MELON_SLICE, "TASTY_MELON_POP", "Tasty Melon Pop"),
      TEA_BURNING = createItem(Items.POTION, "TEA_BURNING", "Tea Burning"),
      TEA_INVISIBLE = createItem(Items.POTION, "TEA_INVISIBLE", "Tea Invisible"),
      TEA_QUICKSTEP = createItem(Items.POTION, "TEA_QUICKSTEP", "Tea Quickstep"),
      TEA_STOMACH = createItem(Items.POTION, "TEA_STOMACH", "Tea Stomach"),
      TEA_STONESKIN = createItem(Items.POTION, "TEA_STONESKIN", "Tea Stoneskin"),
      TECHNICALLY_TURKEY = createItem(Items.COOKED_CHICKEN, "TECHNICALLY_TURKEY", "Technically Turkey"),
      THAUMATURG_BOOTS = createItem(Items.LEATHER_BOOTS, "THAUMATURG_BOOTS", "Thaumaturg Boots"),
      TOKEN_CHRISTMAS = createItem(Items.CLAY_BALL, "TOKEN_CHRISTMAS", "Token Christmas"),
      TOKEN_EASTER = createItem(Items.TURTLE_EGG, "TOKEN_EASTER", "Token Easter"),
      TOKEN_HALLOWEEN = createItem(Items.PUMPKIN, "TOKEN_HALLOWEEN", "Token Halloween"),
      TOKEN_HUNTER_OUTPOST_DESTROYED = createItem(Items.NETHER_BRICK, "TOKEN_HUNTER_OUTPOST_DESTROYED",
          "Token Hunter Outpost Destroyed"),
      TOKEN_HUNTER_PILLAGER = createItem(Items.NETHERITE_INGOT, "TOKEN_HUNTER_PILLAGER", "Token Hunter Pillager"),
      TOKEN_ORIGIN_DAILY = createItem(Items.END_CRYSTAL, "TOKEN_ORIGIN_DAILY", "Token Origin Daily"),
      TOME_COLLAPSING_EARTH_1 = createItem(Items.BOOK, "TOME_COLLAPSING_EARTH_1", "Tome Collapsing Earth 1"),
      TOME_COLLAPSING_EARTH_2 = createItem(Items.BOOK, "TOME_COLLAPSING_EARTH_2", "Tome Collapsing Earth 2"),
      TOME_COLLAPSING_EARTH_3 = createItem(Items.BOOK, "TOME_COLLAPSING_EARTH_3", "Tome Collapsing Earth 3"),
      TOME_COLLAPSING_EARTH_4 = createItem(Items.BOOK, "TOME_COLLAPSING_EARTH_4", "Tome Collapsing Earth 4"),
      TOME_COLLAPSING_EARTH_5 = createItem(Items.BOOK, "TOME_COLLAPSING_EARTH_5", "Tome Collapsing Earth 5"),
      TOME_COLLAPSING_EARTH_6 = createItem(Items.BOOK, "TOME_COLLAPSING_EARTH_6", "Tome Collapsing Earth 6"),
      TOME_CORRUPTION_1 = createItem(Items.BOOK, "TOME_CORRUPTION_1", "Tome Corruption 1"),
      TOME_CORRUPTION_2 = createItem(Items.BOOK, "TOME_CORRUPTION_2", "Tome Corruption 2"),
      TOME_CORRUPTION_3 = createItem(Items.BOOK, "TOME_CORRUPTION_3", "Tome Corruption 3"),
      TOME_CORRUPTION_4 = createItem(Items.BOOK, "TOME_CORRUPTION_4", "Tome Corruption 4"),
      TOME_CORRUPTION_5 = createItem(Items.BOOK, "TOME_CORRUPTION_5", "Tome Corruption 5"),
      TOME_CORRUPTION_6 = createItem(Items.BOOK, "TOME_CORRUPTION_6", "Tome Corruption 6"),
      TOME_FIREBOLT_1 = createItem(Items.BOOK, "TOME_FIREBOLT_1", "Tome Firebolt 1"),
      TOME_FIREBOLT_2 = createItem(Items.BOOK, "TOME_FIREBOLT_2", "Tome Firebolt 2"),
      TOME_FIREBOLT_3 = createItem(Items.BOOK, "TOME_FIREBOLT_3", "Tome Firebolt 3"),
      TOME_FIREBOLT_4 = createItem(Items.BOOK, "TOME_FIREBOLT_4", "Tome Firebolt 4"),
      TOME_FIREBOLT_5 = createItem(Items.BOOK, "TOME_FIREBOLT_5", "Tome Firebolt 5"),
      TOME_FIREBOLT_6 = createItem(Items.BOOK, "TOME_FIREBOLT_6", "Tome Firebolt 6"),
      TOME_FLASH_HEAL_1 = createItem(Items.BOOK, "TOME_FLASH_HEAL_1", "Tome Flash Heal 1"),
      TOME_FLASH_HEAL_2 = createItem(Items.BOOK, "TOME_FLASH_HEAL_2", "Tome Flash Heal 2"),
      TOME_FLASH_HEAL_3 = createItem(Items.BOOK, "TOME_FLASH_HEAL_3", "Tome Flash Heal 3"),
      TOME_FLASH_HEAL_4 = createItem(Items.BOOK, "TOME_FLASH_HEAL_4", "Tome Flash Heal 4"),
      TOME_FLASH_HEAL_5 = createItem(Items.BOOK, "TOME_FLASH_HEAL_5", "Tome Flash Heal 5"),
      TOME_FLASH_HEAL_6 = createItem(Items.BOOK, "TOME_FLASH_HEAL_6", "Tome Flash Heal 6"),
      TOME_FROSTBOLT_1 = createItem(Items.BOOK, "TOME_FROSTBOLT_1", "Tome Frostbolt 1"),
      TOME_FROSTBOLT_2 = createItem(Items.BOOK, "TOME_FROSTBOLT_2", "Tome Frostbolt 2"),
      TOME_FROSTBOLT_3 = createItem(Items.BOOK, "TOME_FROSTBOLT_3", "Tome Frostbolt 3"),
      TOME_FROSTBOLT_4 = createItem(Items.BOOK, "TOME_FROSTBOLT_4", "Tome Frostbolt 4"),
      TOME_FROSTBOLT_5 = createItem(Items.BOOK, "TOME_FROSTBOLT_5", "Tome Frostbolt 5"),
      TOME_FROSTBOLT_6 = createItem(Items.BOOK, "TOME_FROSTBOLT_6", "Tome Frostbolt 6"),
      TOME_LIFE_DRAIN_1 = createItem(Items.BOOK, "TOME_LIFE_DRAIN_1", "Tome Life Drain 1"),
      TOME_LIFE_DRAIN_2 = createItem(Items.BOOK, "TOME_LIFE_DRAIN_2", "Tome Life Drain 2"),
      TOME_LIFE_DRAIN_3 = createItem(Items.BOOK, "TOME_LIFE_DRAIN_3", "Tome Life Drain 3"),
      TOME_LIFE_DRAIN_4 = createItem(Items.BOOK, "TOME_LIFE_DRAIN_4", "Tome Life Drain 4"),
      TOME_LIFE_DRAIN_5 = createItem(Items.BOOK, "TOME_LIFE_DRAIN_5", "Tome Life Drain 5"),
      TOME_LIFE_DRAIN_6 = createItem(Items.BOOK, "TOME_LIFE_DRAIN_6", "Tome Life Drain 6"),
      TOME_PRESSURE_WAVE_1 = createItem(Items.BOOK, "TOME_PRESSURE_WAVE_1", "Tome Pressure Wave 1"),
      TOME_PRESSURE_WAVE_2 = createItem(Items.BOOK, "TOME_PRESSURE_WAVE_2", "Tome Pressure Wave 2"),
      TOME_PRESSURE_WAVE_3 = createItem(Items.BOOK, "TOME_PRESSURE_WAVE_3", "Tome Pressure Wave 3"),
      TOME_PRESSURE_WAVE_4 = createItem(Items.BOOK, "TOME_PRESSURE_WAVE_4", "Tome Pressure Wave 4"),
      TOME_PRESSURE_WAVE_5 = createItem(Items.BOOK, "TOME_PRESSURE_WAVE_5", "Tome Pressure Wave 5"),
      TOME_PRESSURE_WAVE_6 = createItem(Items.BOOK, "TOME_PRESSURE_WAVE_6", "Tome Pressure Wave 6"),
      TOME_REGENERATION_1 = createItem(Items.BOOK, "TOME_REGENERATION_1", "Tome Regeneration 1"),
      TOME_REGENERATION_2 = createItem(Items.BOOK, "TOME_REGENERATION_2", "Tome Regeneration 2"),
      TOME_REGENERATION_3 = createItem(Items.BOOK, "TOME_REGENERATION_3", "Tome Regeneration 3"),
      TOME_REGENERATION_4 = createItem(Items.BOOK, "TOME_REGENERATION_4", "Tome Regeneration 4"),
      TOME_REGENERATION_5 = createItem(Items.BOOK, "TOME_REGENERATION_5", "Tome Regeneration 5"),
      TOME_REGENERATION_6 = createItem(Items.BOOK, "TOME_REGENERATION_6", "Tome Regeneration 6"),
      TOME_RING_OF_MERCY_1 = createItem(Items.BOOK, "TOME_RING_OF_MERCY_1", "Tome Ring Of Mercy 1"),
      TOME_RING_OF_MERCY_2 = createItem(Items.BOOK, "TOME_RING_OF_MERCY_2", "Tome Ring Of Mercy 2"),
      TOME_RING_OF_MERCY_3 = createItem(Items.BOOK, "TOME_RING_OF_MERCY_3", "Tome Ring Of Mercy 3"),
      TOME_RING_OF_MERCY_4 = createItem(Items.BOOK, "TOME_RING_OF_MERCY_4", "Tome Ring Of Mercy 4"),
      TOME_RING_OF_MERCY_5 = createItem(Items.BOOK, "TOME_RING_OF_MERCY_5", "Tome Ring Of Mercy 5"),
      TOME_RING_OF_MERCY_6 = createItem(Items.BOOK, "TOME_RING_OF_MERCY_6", "Tome Ring Of Mercy 6"),
      TORCH_EVERBURNING = createItem(Items.SOUL_TORCH, "TORCH_EVERBURNING", "Torch Everburning"),
      TOTEM_BLOODSNOUT = createItem(Items.WEEPING_VINES, "TOTEM_BLOODSNOUT", "Totem Bloodsnout"),
      TOTEM_CACTUS = createItem(Items.SEA_PICKLE, "TOTEM_CACTUS", "Totem Cactus"),
      TOTEM_KROGNARS = createItem(Items.CLOCK, "TOTEM_KROGNARS", "Totem Krognars"),
      TOTEM_MONTU = createItem(Items.BREWING_STAND, "TOTEM_MONTU", "Totem Montu"),
      TOTEM_STONE = createItem(Items.CHISELED_DEEPSLATE, "TOTEM_STONE", "Totem Stone"),
      TOTEM_UNSETTLING = createItem(Items.SKELETON_SKULL, "TOTEM_UNSETTLING", "Totem Unsettling"),
      TOUGH_ROOTS = createItem(Items.HANGING_ROOTS, "TOUGH_ROOTS", "Tough Roots"),
      TOWN_BLOCK = createItem(Items.PAPER, "TOWN_BLOCK", "Town Block"),
      TURBO_ENCABULATOR = createItem(Items.COMMAND_BLOCK, "TURBO_ENCABULATOR", "Turbo Encabulator"),
      UNCANNY_CUBE = createItem(Items.CONDUIT, "UNCANNY_CUBE", "Uncanny Cube"),
      UNSETTLING_BLADE = createItem(Items.IRON_SWORD, "UNSETTLING_BLADE", "Unsettling Blade"),
      UNSETTLING_BOW = createItem(Items.BOW, "UNSETTLING_BOW", "Unsettling Bow"),
      UNSETTLING_FISHINGPOLE = createItem(Items.FISHING_ROD, "UNSETTLING_FISHINGPOLE", "Unsettling Fishingpole"),
      UNSETTLING_MACE = createItem(Items.BONE, "UNSETTLING_MACE", "Unsettling Mace"),
      WARSCROLL_BLACK_HOLE = createItem(Items.PAPER, "WARSCROLL_BLACK_HOLE", "Warscroll Black Hole"),
      WARSCROLL_DIVINE_INTERVENTION = createItem(Items.PAPER, "WARSCROLL_DIVINE_INTERVENTION",
          "Warscroll Divine Intervention"),
      WARSCROLL_EXPLODING_FOWL = createItem(Items.PAPER, "WARSCROLL_EXPLODING_FOWL", "Warscroll Exploding Fowl"),
      WARSCROLL_METEOR = createItem(Items.PAPER, "WARSCROLL_METEOR", "Warscroll Meteor"),
      WARSCROLL_OVERLOAD = createItem(Items.PAPER, "WARSCROLL_OVERLOAD", "Warscroll Overload"),
      WAR_BOND = createItem(Items.PAPER, "WAR_BOND", "War Bond"),
      WAR_SUPPLIES = createItem(Items.BARREL, "WAR_SUPPLIES", "War Supplies"),
      WEAPON_POMMEL = createItem(Items.TRIPWIRE_HOOK, "WEAPON_POMMEL", "Weapon Pommel"),
      WELL_SEASONED_BEEF = createItem(Items.COOKED_BEEF, "WELL_SEASONED_BEEF", "Well Seasoned Beef"),
      WELL_SEASONED_CHICKEN = createItem(Items.COOKED_CHICKEN, "WELL_SEASONED_CHICKEN", "Well Seasoned Chicken"),
      WELL_SEASONED_COD = createItem(Items.COOKED_COD, "WELL_SEASONED_COD", "Well Seasoned Cod"),
      WELL_SEASONED_MUTTON = createItem(Items.COOKED_MUTTON, "WELL_SEASONED_MUTTON", "Well Seasoned Mutton"),
      WELL_SEASONED_PORKCHOP = createItem(Items.COOKED_PORKCHOP, "WELL_SEASONED_PORKCHOP", "Well Seasoned Porkchop"),
      WELL_SEASONED_PUFFERFISH = createItem(Items.PUFFERFISH, "WELL_SEASONED_PUFFERFISH", "Well Seasoned Pufferfish"),
      WELL_SEASONED_RABBIT = createItem(Items.COOKED_RABBIT, "WELL_SEASONED_RABBIT", "Well Seasoned Rabbit"),
      WELL_SEASONED_SALMON = createItem(Items.COOKED_SALMON, "WELL_SEASONED_SALMON", "Well Seasoned Salmon"),
      WELL_SEASONED_TROPICAL_FISH = createItem(Items.TROPICAL_FISH, "WELL_SEASONED_TROPICAL_FISH",
          "Well Seasoned Tropical Fish"),
      WHIPPING_WIND = createItem(Items.BONE_MEAL, "WHIPPING_WIND", "Whipping Wind"),
      WHOLE_WART = createItem(Items.RED_DYE, "WHOLE_WART", "Whole Wart"),
      WHOLE_WART_BREAD = createItem(Items.BREAD, "WHOLE_WART_BREAD", "Whole Wart Bread"),
      WIZARDS_BOOTS = createItem(Items.LEATHER_BOOTS, "WIZARDS_BOOTS", "Wizards Boots"),
      WIZARDS_CHESTPLATE = createItem(Items.LEATHER_CHESTPLATE, "WIZARDS_CHESTPLATE", "Wizards Chestplate"),
      WIZARDS_HELMET = createItem(Items.LEATHER_HELMET, "WIZARDS_HELMET", "Wizards Helmet"),
      WIZARDS_LEGGINGS = createItem(Items.LEATHER_LEGGINGS, "WIZARDS_LEGGINGS", "Wizards Leggings"),
      WOODEN_AXE = createItem(Items.WOODEN_AXE, "WOODEN_AXE", "Wooden Axe"),
      WOODEN_BOOTS = createItem(Items.LEATHER_BOOTS, "WOODEN_BOOTS", "Wooden Boots"),
      WOODEN_CHESTPLATE = createItem(Items.LEATHER_CHESTPLATE, "WOODEN_CHESTPLATE", "Wooden Chestplate"),
      WOODEN_HELMET = createItem(Items.LEATHER_HELMET, "WOODEN_HELMET", "Wooden Helmet"),
      WOODEN_HOE = createItem(Items.WOODEN_HOE, "WOODEN_HOE", "Wooden Hoe"),
      WOODEN_LEGGINGS = createItem(Items.LEATHER_LEGGINGS, "WOODEN_LEGGINGS", "Wooden Leggings"),
      WOODEN_MACE = createItem(Items.STICK, "WOODEN_MACE", "Wooden Mace"),
      WOODEN_PICKAXE = createItem(Items.STONE_PICKAXE, "WOODEN_PICKAXE", "Wooden Pickaxe"),
      WOODEN_SHIELD = createItem(Items.DEAD_BUSH, "WOODEN_SHIELD", "Wooden Shield"),
      WOODEN_SHOVEL = createItem(Items.WOODEN_SHOVEL, "WOODEN_SHOVEL", "Wooden Shovel"),
      WOOL_BOOTS = createItem(Items.LEATHER_BOOTS, "WOOL_BOOTS", "Wool Boots"),
      WOOL_CHESTPLATE = createItem(Items.LEATHER_CHESTPLATE, "WOOL_CHESTPLATE", "Wool Chestplate"),
      WOOL_HELMET = createItem(Items.LEATHER_HELMET, "WOOL_HELMET", "Wool Helmet"),
      WOOL_LEGGINGS = createItem(Items.LEATHER_LEGGINGS, "WOOL_LEGGINGS", "Wool Leggings"),
      ZOMBIE_LEATHER = createItem(Items.LEATHER, "ZOMBIE_LEATHER", "Zombie Leather");

  public static void addItems(EmiRegistry registry) {
    ITEMS.forEach((k, v) -> {
      registry.addEmiStack(v);
    });
  }
}
